### ISSUE TITLE
how to use it in OC project?

### ISSUE THREAD

**Issue by zziazm** [iosdevzone/IDZSwiftCommonCrypto#102]
how to use it in OC project?

**Comment by iosdevzone** [comment]
Hi @zziazm, what is an OC project?

**Comment by zziazm** [comment]
I create Objective-C project, can I use IDZSwiftCommonCrypto in Objective-C?

**Comment by iosdevzone** [comment]
Hi @zziazm,

No, you can't use IDZSwiftCommonCrypto in an Objective-C project.
