### ISSUE TITLE
Facing crash issue in Xcode 11 and Xcode 11.1

### ISSUE THREAD

**Issue by sundar05** [iosdevzone/IDZSwiftCommonCrypto#105]
I have updated new Xcode 11 and updated the pod 'IDZSwiftCommonCrypto', '0.13.0', But now facing the crash issue. Thread 1: Fatal error: FATAL_ERROR: Invalid initialization vector size. Please fix the issue as soon as possible very urgent.

**Comment by iosdevzone** [comment]
This is not a bug. It is an error in your code. For modes that require an initialization vector you must pass an initialization vector of the correct length. What allowed you to do this in past versions was a bug in `IDZSwiftCommonCrypto` -- it would accept initialization vectors of incorrect length, possibly reading uninitialized memory.

**Comment by iosdevzone** [comment]
I've just merged some improved demo code showing how to deal with initialization vectors. See PR #106 for the changes and clone master to see it running in a playground. Hope this helps!
