### ISSUE TITLE
How to decrypt large encrypted data?

### ISSUE THREAD

**Issue by PGandhi30** [iosdevzone/IDZSwiftCommonCrypto#107]
a large amount of data received = 43355488 bytes (payload as Data)
I try your function for decrypt data and it takes a large amount of device memory.

let iv:[UInt8] = Array(IV_KEY.utf8)
let bytes = Array([UInt8](payload)[0  ..< count])
let aesDecrypt = Cryptor(operation: .decrypt, algorithm: .aes, mode: .CBC, padding: .NoPadding, key: key, iv: iv)
 
if let decrypted = aesDecrypt.update(data: payload)?.final() {
     return String(bytes: decrypted, encoding: .utf8)
}

Is any possible solution to make a data chunk and decrypt it?

**Comment by iosdevzone** [comment]
For large amounts of data you should use `StreamCryptor`. Please see the README.md or README.playground for an example of how to use it.
