### ISSUE TITLE
error on installing pod

### ISSUE THREAD

**Issue by Nurka11** [iosdevzone/IDZSwiftCommonCrypto#108]
[!] /bin/bash -c 
set -e
touch prepare_command.txt
echo 'Running prepare_command'
pwd
echo Running GenerateCommonCryptoModule
# This was needed to ensure the correct Swift interpreter was 
# used in Xcode 8. Leaving it here, commented out, in case similar 
# issues occur when migrating to Swift 4.0.
#TC="--toolchain com.apple.dt.toolchain.Swift_2_3"
SWIFT="xcrun $TC swift"
$SWIFT ./GenerateCommonCryptoModule.swift macosx .
$SWIFT ./GenerateCommonCryptoModule.swift iphonesimulator .
$SWIFT ./GenerateCommonCryptoModule.swift iphoneos .
$SWIFT ./GenerateCommonCryptoModule.swift appletvsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift appletvos .
$SWIFT ./GenerateCommonCryptoModule.swift watchsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift watchos .

Running prepare_command
/Users/apple/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.10.0-4eef2
Running GenerateCommonCryptoModule
./GenerateCommonCryptoModule.swift:15:34: error: 'characters' is unavailable: Please use String directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^~~~~~~~~~
Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
    public var characters: String { get set }
               ^

**Comment by iosdevzone** [comment]
OK, so the problem is you are trying to use IDZSwiftCommonCrypto version 0.10.0 with Swift 5. That will not work. You need to use at least version 0.12.0. You can find more about which version of the library to use with which versions of Swift and Xcode in the [README.md](https://github.com/iosdevzone/IDZSwiftCommonCrypto/blob/master/README.md).
