### ISSUE TITLE
21 Xcode Warnings Around Digest Calculator

### ISSUE THREAD

**Issue by emtjoshhart** [iosdevzone/IDZSwiftCommonCrypto#118]
'CC_MD2_Update' was deprecated in iOS 13.0: This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger).

21 Warnings surrounding CC_MD2, CC_MD4 and CC_MD5

**Comment by iosdevzone** [comment]
This is indeed true, but if you may still need to calculate MD2, MD4 or MD5 for example to interact with a legacy system.
