### ISSUE TITLE
Xcode 13 Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by PixoDev** [iosdevzone/IDZSwiftCommonCrypto#121]
Hi,

I know this issue is not related to the library itself, mostly my target configuration, but I'm having a hard time trying to figure the problem out.

![debug-x86_64](https://user-images.githubusercontent.com/42890253/171052288-be88083f-c9a1-46b6-8ae1-4ad672102369.png)

Saw this issue that I guess is kinda related:

https://github.com/iosdevzone/IDZSwiftCommonCrypto/issues/42

But already checked all my Pods and the architecture settings are ok I guess

![87584f3400f464adfc7d34313d747f26](https://user-images.githubusercontent.com/42890253/171052612-3dc7d6cf-a3ac-4eed-912c-fd4564b5f51f.png)

Is anything that I'm missing from this? Any pointer about how can I debug this?

Thanks for your help!

**Comment by PixoDev** [comment]
Cocoapods issue, fixed luckily :)

**Comment by iosdevzone** [comment]
Glad you found a solution!
