### ISSUE TITLE
DES ECB zeroPadding support

### ISSUE THREAD

**Issue by Lobooo** [iosdevzone/IDZSwiftCommonCrypto#124]
Hi @iosdevzone,
I am working on iOS swift project that encrypts transfer data with DES ECB zeroPadding. Luckily, I found your repo and tried to implement it for my project. Below is my testing crypto code. It works well with PKCS7Padding, but did not work with zeroPadding

func encrypt(newsid: String) -> String? {
    let key = Array("(#i@x*l%".utf8)
    let bytes = Array(newsid.utf8)
    let cryptor = Cryptor(operation: .encrypt, algorithm: .des, options: [.ECBMode, .PKCS7Padding], key: key, iv:[UInt8]())
    if let encrypted = cryptor.update(byteArray: bytes)?.final() {
        return encrypted.toHexString()
    }
    return nil
}

**Comment by iosdevzone** [comment]
Hi @Lobooo 

Can you give me an example of input you are giving, the output you are getting and the output you expect to get?

**Comment by Lobooo** [comment]
Hi idz,

Input: ”651148”, output: ”2e20f24a9b66ccb5” is the correct string, but it return nil

Thanks!

**Comment by iosdevzone** [comment]
What padding did you use and how did you conclude that "2e20f24a9b66ccb5" is the correct answer?

**Comment by Lobooo** [comment]
http://tool.chacuo.net/cryptdesIn this link, you can did param. setting as follow: DES加密模式: -> ***@***.****l%发自我的iPhone------------------ Original ------------------From: idz  ***@***.***>Date: Fri,Nov 4,2022 0:07 PMTo: iosdevzone/IDZSwiftCommonCrypto ***@***.***>Cc: Lobooo ***@***.***>, Mention ***@***.***>Subject: Re: [iosdevzone/IDZSwiftCommonCrypto] DES ECB zeroPadding support(Issue #124)
What padding did you use and how did you conclude that "2e20f24a9b66ccb5" is the correct answer?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iosdevzone/IDZSwiftCommonCrypto/issues/124#issuecomment-1302932190",
"url": "https://github.com/iosdevzone/IDZSwiftCommonCrypto/issues/124#issuecomment-1302932190",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Lobooo** [comment]
And setting 输出：->  hex, then press the yellow button “DES加密”发自我的iPhone------------------ Original ------------------From: Lobo  ***@***.***>Date: Fri,Nov 4,2022 0:20 PMTo: iosdevzone/IDZSwiftCommonCrypto ***@***.***>Subject: Re: [iosdevzone/IDZSwiftCommonCrypto] DES ECB zeroPadding support(Issue #124)http://tool.chacuo.net/cryptdesIn this link, you can did param. setting as follow: DES加密模式: -> ***@***.****l%发自我的iPhone------------------ Original ------------------From: idz  ***@***.***>Date: Fri,Nov 4,2022 0:07 PMTo: iosdevzone/IDZSwiftCommonCrypto ***@***.***>Cc: Lobooo ***@***.***>, Mention ***@***.***>Subject: Re: [iosdevzone/IDZSwiftCommonCrypto] DES ECB zeroPadding support(Issue #124)
What padding did you use and how did you conclude that "2e20f24a9b66ccb5" is the correct answer?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iosdevzone/IDZSwiftCommonCrypto/issues/124#issuecomment-1302932190",
"url": "https://github.com/iosdevzone/IDZSwiftCommonCrypto/issues/124#issuecomment-1302932190",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iosdevzone** [comment]
I couldn't access the online tool you are using, but looking at the output, it is using zero padding and an initialization vector of all zeroes.

You can prove this using this code 

```swift
import Foundation
import IDZSwiftCommonCrypto

func decrypt(bytes: [UInt8]) -> [UInt8]? {
    let key = Array("(#i@x*l%".utf8)
    let iv = Array(repeating: UInt8(0), count: Cryptor.Algorithm.des.blockSize())
    let cryptor = Cryptor(operation: .decrypt, algorithm: .des, options: [.ECBMode, .None], key: key, iv: iv)
    if let decrypted = cryptor.update(byteArray: bytes)?.final() {
        return decrypted
    }
    return nil
}

let hexStringCiphertext = "2e20f24a9b66ccb5"
let bytes = arrayFrom(hexString: hexStringCiphertext)
if let decrypted = decrypt(bytes: bytes), let decryptedString = String(bytes: decrypted, encoding: .utf8) {
    print(decryptedString)
}
```

You can match this encoding by making the following changes to your code:

```swift
func encrypt(newsid: String) -> String? {
    let key = Array("(#i@x*l%".utf8)
    let bytes = Array(newsid.utf8)
    let blockSize = Cryptor.Algorithm.des.blockSize()
    // The initialization vector should be a one time
    // random array of bytes. But it looks like the online
    // encoder you are using just uses a block of zero bytes.
    let iv = Array(repeating: UInt8(0), count: blockSize)
    // Zero pad the bytes to ensure there are an integral number of
    // blocks long. For DES the block size is 8 bytes.
    let paddedBytes = zeroPad(array: bytes, blockSize: blockSize)
    // If this assertion fails, the encryption will also fail.
    // It means you are not correctly padding.
    assert(paddedBytes.count % blockSize == 0)
    let cryptor = Cryptor(operation: .encrypt, algorithm: .des, options: [.ECBMode, .None], key: key, iv: iv)
    if let encrypted = cryptor.update(byteArray: paddedBytes)?.final() {
        return hexString(fromArray: encrypted)
    }
    return nil
}
```
