### ISSUE TITLE
Why does final return Array<UInt8> and not string?

### ISSUE THREAD

**Issue by AndreasHeiberg** [iosdevzone/IDZSwiftCommonCrypto#15]
Hi,

I figured out that you can convert `Array<UInt8>` to a string using `hexStringFromArray()`.

I was just wondering, why is this not the default return value?

Thanks,

**Comment by iosdevzone** [comment]
Because, except to print out, a hex string is rarely what you want. Most protocols use the binary value of the calculation (be it a Digest, HMAC, or Encryption/Decryption)

**Comment by AndreasHeiberg** [comment]
I read something similar about NSJSONSerialization I believe. Really weird coming from a PHP, Ruby, JS, Python pretty much any language I can think of having used for an extended period except for Objective-C perhaps.

But I guess that's just how it is :)
