### ISSUE TITLE
OS X 10.10 Support

### ISSUE THREAD

**Issue by SunshinyNeko** [iosdevzone/IDZSwiftCommonCrypto#16]
Module file's minimum deployment target is OS X 10.11

Please support OS X 10.10

<img width="291" alt="screen shot 2016-01-15 at 10 30 25" src="https://cloud.githubusercontent.com/assets/15274326/12343921/121e5f14-bb73-11e5-8c52-900bb6010755.png">

**Comment by SunshinyNeko** [comment]
And Xcode 7.2 crashed...

**Comment by iosdevzone** [comment]
The OS X deployment version is 10.10 in release 0.7.2.

Please report Xcode crashes to http://bugreport.apple.com.
