### ISSUE TITLE
Is AES-CFB stream cipher mode supported?

### ISSUE THREAD

**Issue by UnsignedInt8** [iosdevzone/IDZSwiftCommonCrypto#17]
Hi, I tried to use StreamCryptor to encrypt data, but it seemed to be CBC mode. I think CBC is not real stream cipher. Can I use AES CFB mode to encrypt data?

Swift:
let sc = StreamCryptor(operation: .Encrypt, algorithm: .AES, options: .None, key: key, iv: iv)

Node.js:
var aes256cbc = crypto.createCipheriv('aes-256-cbc', key, iv)

Some data encrypted by them are same.

**Comment by UnsignedInt8** [comment]
I found these code at CommonCrypto.h, please make IDZSwiftCommonCrypto support it, thank you.

<img width="647" alt="screen shot 2016-02-01 at 16 34 19" src="https://cloud.githubusercontent.com/assets/15274326/12712282/3a990830-c902-11e5-834f-b49faec7f2cc.png">

**Comment by iosdevzone** [comment]
You are correct, `StreamCryptor`, by default uses CBC mode, by default. The Stream in `StreamCryptor` refers to the fact that is can be used to encrypt streams... not that it is operating in a streaming cipher mode. Yes, it is a little confusing. It can't be helped.

The modes you are mentioning must have been introduced recently. The problem with supporting them in the main branch is that it (may) break compatibility for people targeting older systems. Over the next couple of days I'll create a branch with these new modes and test them out.

If you have made any progress adding support for them yourself, please feel free to send me a pull request.

**Comment by UnsignedInt8** [comment]
Oh, sorry. I'm not familiar with Objective-C and C, so I have to use 3rd library to get CommonCrypto-features. 

I hope IDZSwiftCommonCrypto will support CFB and other modes in the future. :)

Thank you.

**Comment by mdab121** [comment]
I was facing the same issue. Check out my pull request: #29

**Comment by iosdevzone** [comment]
Michał's pull request #29 is now available in 0.8.0 for Swift 2.x. This provides support for `CCMode`s
