### ISSUE TITLE
Cocoapod support.

### ISSUE THREAD

**Issue by datomnurdin** [iosdevzone/IDZSwiftCommonCrypto#2]
Is there any cocoapod support for this library? Thanks.

**Comment by iosdevzone** [comment]
Hi Mohammad,
Currently there is no CocoaPods support. It's pretty easy just to drag the project into your own. 
I you would like to create and maintain a podspec for it I'll happily accept the pull request.
idz

**Comment by iosdevzone** [comment]
Cocoapods is now supported on the swift2.0 branch. 
See https://cocoapods.org/pods/IDZSwiftCommonCrypto
