### ISSUE TITLE
Swift 2.2

### ISSUE THREAD

**Issue by AleksandarPetrov** [iosdevzone/IDZSwiftCommonCrypto#21]
After the new Xcode and Swift update, I was not able to compile my project, because an error in modulemap file. I've made the following changes.

  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonCrypto.h"
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonRandom.h"

**Comment by Huralnyk** [comment]
Thank you, Aleksandr! Your comment helped me a lot.

**Comment by iosdevzone** [comment]
Hi folks, 
Sorry I have not responded earlier... my day job sometimes gets in the way. 
I am a little behind in Xcode versions, I will update and try to put consistent fixes into the repo.
Thanks for your patience,
Danny

**Comment by iosdevzone** [comment]
I believe this problem is solved in version 0.7.4, if not please reopen this issue with more details (e.g. are you using CocoaPods, Carthage or the supplied project file).
