### ISSUE TITLE
Decrypt Plain Text

### ISSUE THREAD

**Issue by victtavares** [iosdevzone/IDZSwiftCommonCrypto#25]
Hi,

I'm receiving an string from my webservice using a base64 encoding. Is there any way to decrypt it using the Cryptor function?

I'm currently doing the following:

```
let value = "textToDecrypt"
let initialKey = PBKDF.deriveKey("KEY", salt: "SALT", prf: .SHA1, rounds: 1000, derivedKeyLength: 60)
var computedkey = Array(initialKey[0..<32])
var computedIV = Array(initialKey[32..<48])

let cryptor = Cryptor(operation:.Decrypt, algorithm:.AES, options:.PKCS7Padding, key:computedkey, iv:computedIV)
let decryptedPlainText = cryptor.update(Array(value.utf8))?.final()
let decryptedString = decryptedPlainText!.reduce("") { $0 + String(UnicodeScalar($1)); }
print(decryptedString)

```
After debugging it, it just outputs a lot of strange characters..
"èÁK7;ýø«Wh{4}gÅíïG}úÆ&¢	]Em«Em"

PS: The example above works when I use the [UInt8] array from the cryptor encrypt function instead of "Array(value.utf8)"

**Comment by iosdevzone** [comment]
Hi,
Before passing it to the `Cryptor` you will need to undo the base64 encoding. The `NSData` class in foundation can do this for you.
