### ISSUE TITLE
And then decrpyt?

### ISSUE THREAD

**Issue by byroncoetsee** [iosdevzone/IDZSwiftCommonCrypto#26]
Hi guys,

Thanks for the great tool!

However, once I have encrypted something with SHA256, how do I decrypt it again?
I can't seem to find any docs on that...

Thanks

**Comment by iosdevzone** [comment]
Hi Byron,

SHA256 is a hashing algorithm not an encryption algorithm (so there is no way to decrypt it). If you want to to encrypt and decrypt you will need to use an encryption/decryption algorithm (see `StreamCryptor` or `Cryptor` classes).

Hope this helps,
idz
