### ISSUE TITLE
Blowfish ECB discrepancy

### ISSUE THREAD

**Issue by lawallet** [iosdevzone/IDZSwiftCommonCrypto#27]
I'm currently using blowfish to send encrypted data to a webservice. The server itself is using mcrypt for handling decrypting the data, but what I get when encrypting with the library is different than what mcrypt outputs. For example, when encrypting (and converting to a base64 string) enctest01@test.com with a key of testtesttesttest I get "dSDG4kXkIj5Pc6/M3jo6nlDnoB62dcX9" (using https://www.tools4noobs.com/online_tools/encrypt/ for a quick test) the output is fine, but when I use something more complex the issue occurs. 
Code snippet
```
let blockSize = Cryptor.Algorithm.Blowfish.blockSize()
        let plainText = zeroPad("arbitray long data", blockSize)
        var tempIv = arrayFromString("")
        let cryptor = Cryptor(operation: .Encrypt, algorithm: .Blowfish, options: .ECBMode, key: key, iv: Array<UInt8>())
        var cipherText = cryptor.update(plainText)?.final()
        var cipherArrData = dataFromByteArray(cipherText!)
        var cipherTest = cipherArrData.base64EncodedStringWithOptions(.Encoding64CharacterLineLength)
```

**Comment by lawallet** [comment]
Forgot that

**Comment by iosdevzone** [comment]
Hi there,
Sorry for the delay in responding. Please send me what your inputs are, what output you are getting and what output you were expecting. I'll do my best to help you out.
idz

**Comment by lawallet** [comment]
Using key: WW_183748_JdO1 and PlainText: {\"TestData\":{\"TestID\":\"553-20177822\",\"TestNum\":17,\"Event\":\"TestEvent\"}}

The site gives me: 704lP1fCYaWG/YuiUIaHIchF968c6oLR/x8KtQjpyXUOjgyc/cl4ApSnP2A4snkIbThXRlsQiAaorCaf6Acpm4Dm6HnMnXJGSRQSkF7vVEl6S2y4jh8YHg==

Library gives me: kBqa6ZkRhsqHx1TjwwcuNBeDAGHOcC1q7yKdEClILm3DpIyt6dEuvJgCoJ4hOJnE\r\nPK9+PU/PF4vRIShXLoNh2fyoOEBPz7Zs

**Comment by iosdevzone** [comment]
OK, I see what's going on. The backslashes are escape characters. You need to remove them for the website.

So while you Swift code looks like this:
````swift
let key = arrayFromString("WW_183748_JdO1")
let blockSize = Cryptor.Algorithm.Blowfish.blockSize()
let plainText = zeroPad("{\"TestData\":{\"TestID\":\"553-20177822\",\"TestNum\":17,\"Event\":\"TestEvent\"}}", blockSize)
````

On the site you enter:
````
{"TestData":{"TestID":"553-20177822","TestNum":17,"Event":"TestEvent"}}
````

If you do this, both will give you the same result:
````
kBqa6ZkRhsqHx1TjwwcuNBeDAGHOcC1q7yKdEClILm3DpIyt6dEuvJgCoJ4hOJnEPK9+PU/PF4vRIShXLoNh2fyoOEBPz7Zs
````

**Comment by lawallet** [comment]
Gah, don't know how I forgot about escape characters, thanks

**Comment by iosdevzone** [comment]
Can happen to the best of us ;-)
