### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by vinced45** [iosdevzone/IDZSwiftCommonCrypto#31]
Do you have plans to update to Swift 3.0? Thanks

**Comment by JonB** [comment]
I have created a fork (for now) that works with Swift 3.0: https://github.com/JonB/IDZSwiftCommonCrypto

There are plenty of warnings which need to be fixed up and I have removed `Cryptor.swift` and `StreamCryptor.swift` from the target for now as we don't require them and I couldn't solve a couple of issues these raised.

**Comment by AsTryE** [comment]
@JonB could install IDZSwiftCommonCrypto by cocoapods ?

**Comment by JonB** [comment]
@AsTryE not sure I follow...?

**Comment by AsTryE** [comment]
ye, i see you created a created a fork that works with Swift 3.0: https://github.com/JonB/IDZSwiftCommonCrypto PR:#32, Sorry i dont kown to it 。now my project to swift 3，but this IDZSwiftCommonCrypto none swift3 branch，how can i solve it.thks!

**Comment by AsTryE** [comment]
@JonB i know, thks !

**Comment by bmt22033** [comment]
@JonB Hi Jon.  Thanks for your work migrating this to Swift 3.0!  I've updated my Podfile with this line:

`pod 'IDZSwiftCommonCrypto', :git => 'https://github.com/JonB/IDZSwiftCommonCrypto'`

When I run `pod install`, I see v0.7.2 being installed and it appears to work correctly.  However, when I run `pod outdated`, it tells me that v0.7.3 is the latest version.  Should I be pointing somewhere else to get this version?

**Comment by JonB** [comment]
@iosdevzone will you get chance to have a look at the PR's at all? Would be good to get something merged into your master repo and bump the version on Cocoapods / Carthage.

**Comment by iosdevzone** [comment]
Apologies, I've been slammed at my day job, I am really hoping to get a chance to look at it over this coming weekend. I'm very appreciative of all the work others have done on this project.

**Comment by JonB** [comment]
Thanks @iosdevzone really appreciated.

**Comment by iosdevzone** [comment]
@JonB just did a quick visual review of your edits and they look great. In some places your Swiftication was more thorough than I might have done (e.g. .MD5 -> .md5), but I think your strictness is better and more in keeping with that Apple have outlined. 

My plan is to do two or three releases over the next few days, the final one essentially being your pull request with some tweaks to the coverage settings. Since the Swift 3.0 release is breaking I just want one or two intermediate release for folks not ready to take the jump jet.

Once again thanks for your work and sorry I have been slow to react to the PRs.

**Comment by JonB** [comment]
Don't worry about being slow - I'm just lucky to have a day job that allowed me to have worked on this 👍 

I would totally check out #30 which my work colleague started with. I built on top of this, but it's probably a good first step. Swift 2.3 support with very minimal API changes.

**Comment by kimar** [comment]
@iosdevzone this issue can be close as #30 and #32 have been merged.

**Comment by iosdevzone** [comment]
@kimar Beat me to it. Just in the middle of making sure I didn't mess up any of the hard work done by you and your co-worker ;-)

**Comment by Tibb** [comment]
According to Cocoapods, iOS 10 seems to be the only supported Deployment Target. It was not the case with the initial @JonB fork. Any chance to revert back to iOS 9.x ?
You know how outdated users with previous iOS versions are important :) thx

**Comment by kimar** [comment]
@Tibb that's weird, the podspec says iOS 9.3 (https://github.com/CocoaPods/Specs/blob/master/Specs/IDZSwiftCommonCrypto/0.9.0/IDZSwiftCommonCrypto.podspec.json) and the project file even specifies iOS 8.0 as minimum target...

**Comment by Tibb** [comment]
@kimar Indeed.. I removed it, re-checked all my targets, found one with 9.0 ( 👎 ), switched everything to 9.3 and.. it worked.
Thanks a lot and sorry to bothered you with my lack of verification.. :)

**Comment by iosdevzone** [comment]
Apologies for the inconvenience @Tibb I was probably overly aggressive with the version in the podfile, but it took a while to get it to work. Thanks for the assist @kimar!
