### ISSUE TITLE
cocoapods error

### ISSUE THREAD

**Issue by AsTryE** [iosdevzone/IDZSwiftCommonCrypto#33]
hello
xcode8  
pod --version
1.1.0.beta.2
pod install
error:
.....
Installing IDZSwiftCommonCrypto (0.7.3)
.......
[!] /bin/bash -c 
set -e
touch prepare_command.txt
echo 'Running prepare_command'
pwd
echo Running GenerateCommonCryptoModule
swift ./GenerateCommonCryptoModule.swift macosx .
swift ./GenerateCommonCryptoModule.swift iphonesimulator .
swift ./GenerateCommonCryptoModule.swift iphoneos .
swift ./GenerateCommonCryptoModule.swift appletvsimulator .
swift ./GenerateCommonCryptoModule.swift appletvos .
swift ./GenerateCommonCryptoModule.swift watchsimulator .
swift ./GenerateCommonCryptoModule.swift watchos .

Running prepare_command
/Users/gongxinying/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.7.3-f4271
Running GenerateCommonCryptoModule
./GenerateCommonCryptoModule.swift:55:1: error: '@noreturn' has been removed; functions that never return should have a return type of 'Never' instead
@noreturn func reportError(message: String) {
^~~~~~~~~~
                                            -> Never 
./GenerateCommonCryptoModule.swift:73:31: error: instance member 'arguments' cannot be used on type 'Process'
guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
                              ^~~~~~~ ~~~~~~~~~
./GenerateCommonCryptoModule.swift:73:82: error: missing argument label 'message:' in call
guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
                                                                                 ^
                                                                                 message: 
./GenerateCommonCryptoModule.swift:17:22: error: 'NSPipe' has been renamed to 'Pipe'
    let outputPipe = NSPipe()
                     ^~~~~~
                     Pipe
./GenerateCommonCryptoModule.swift:18:16: error: 'NSTask' has been renamed to 'Process'
    let task = NSTask()
               ^~~~~~
               Process
./GenerateCommonCryptoModule.swift:33:12: error: 'NSFileManager' has been renamed to 'FileManager'
    return NSFileManager.defaultManager().fileExistsAtPath(filePath)
           ^~~~~~~~~~~~~
           FileManager
./GenerateCommonCryptoModule.swift:38:13: error: 'NSFileManager' has been renamed to 'FileManager'
        try NSFileManager.defaultManager().createDirectoryAtPath(path, withIntermediateDirectories: true, attributes: nil)
            ^~~~~~~~~~~~~
            FileManager
./GenerateCommonCryptoModule.swift:48:108: error: cannot call value of non-function type 'CharacterSet'
    return ((s as NSString).stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet()) as String)
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                                                                           
./GenerateCommonCryptoModule.swift:52:37: error: missing argument label 's:' in call
    return (s == nil) ? nil : (trim(s!) as String)
                                    ^
                                    s: 
./GenerateCommonCryptoModule.swift:89:4: error: instance member 'arguments' cannot be used on type 'Process'
if Process.arguments.count > 2 {
   ^~~~~~~ ~~~~~~~~~
./GenerateCommonCryptoModule.swift:97:19: error: missing argument label 'filePath:' in call
    if fileExists(moduleDirectory) {
                  ^
                  filePath: 
./GenerateCommonCryptoModule.swift:98:21: error: missing argument label 'message:' in call
        reportError("Module directory already exists at \(moduleDirectory).")
                    ^
                    message: 
./GenerateCommonCryptoModule.swift:102:11: error: missing argument label 'path:' in call
if !mkdir(moduleDirectory) {
          ^
          path: 
./GenerateCommonCryptoModule.swift:103:17: error: missing argument label 'message:' in call
    reportError("Failed to create module directory \(moduleDirectory)")
                ^
                message: 
./GenerateCommonCryptoModule.swift:124:17: error: missing argument label 'message:' in call
    reportError("Failed to write module map file to \(moduleMapPath)")
                ^
                message:

**Comment by mironal** [comment]
I have same issue. xcode 8

**Comment by JonB** [comment]
Try the swift 2.3 or 3 pull request branches: #32 (Swift3) #30 (Swift2.3)

**Comment by AsTryE** [comment]
thks

**Comment by iosdevzone** [comment]
This was caused by the podfile not specifying the toolchain to be used to run the `GenerateCommonCryptoModule.swift` script.
 
I have pushed a version 0.8.1 to cocoapods that solves this problem.

**Comment by seanvikoren** [comment]
Greetings,
I am seeing this still:
Xcode Version 8.0 (8A218a)

$ pod _1.1.0.rc.2_ --version
1.1.0.rc.2

$ pod _1.1.0.rc.2_ update
...
Installing IDZSwiftCommonCrypto (0.8.1)
[!] /bin/bash -c 
set -e
touch prepare_command.txt
echo 'Running prepare_command'
pwd
echo Running GenerateCommonCryptoModule
swift ./GenerateCommonCryptoModule.swift macosx .
swift ./GenerateCommonCryptoModule.swift iphonesimulator .
swift ./GenerateCommonCryptoModule.swift iphoneos .
swift ./GenerateCommonCryptoModule.swift appletvsimulator .
swift ./GenerateCommonCryptoModule.swift appletvos .
swift ./GenerateCommonCryptoModule.swift watchsimulator .
swift ./GenerateCommonCryptoModule.swift watchos .

Running prepare_command
/Users/sean/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.8.1-0fe7e
Running GenerateCommonCryptoModule
./GenerateCommonCryptoModule.swift:55:1: error: '@noreturn' has been removed; functions that never return should have a return type of 'Never' instead
@noreturn func reportError(message: String) {
^~~~~~~~~~
                                            -> Never 
./GenerateCommonCryptoModule.swift:73:31: error: instance member 'arguments' cannot be used on type 'Process'
guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
                              ^~~~~~~ ~~~~~~~~~
./GenerateCommonCryptoModule.swift:73:82: error: missing argument label 'message:' in call
guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
                                                                                 ^
                                                                                 message: 
./GenerateCommonCryptoModule.swift:17:22: error: 'NSPipe' has been renamed to 'Pipe'
    let outputPipe = NSPipe()
                     ^~~~~~
                     Pipe
./GenerateCommonCryptoModule.swift:18:16: error: 'NSTask' has been renamed to 'Process'
    let task = NSTask()
               ^~~~~~
               Process
./GenerateCommonCryptoModule.swift:33:12: error: 'NSFileManager' has been renamed to 'FileManager'
    return NSFileManager.defaultManager().fileExistsAtPath(filePath)
           ^~~~~~~~~~~~~
           FileManager
./GenerateCommonCryptoModule.swift:38:13: error: 'NSFileManager' has been renamed to 'FileManager'
        try NSFileManager.defaultManager().createDirectoryAtPath(path, withIntermediateDirectories: true, attributes: nil)
            ^~~~~~~~~~~~~
            FileManager
./GenerateCommonCryptoModule.swift:48:108: error: cannot call value of non-function type 'CharacterSet'
    return ((s as NSString).stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet()) as String)
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                                                                                                           
./GenerateCommonCryptoModule.swift:52:37: error: missing argument label 's:' in call
    return (s == nil) ? nil : (trim(s!) as String)
                                    ^
                                    s: 
./GenerateCommonCryptoModule.swift:89:4: error: instance member 'arguments' cannot be used on type 'Process'
if Process.arguments.count > 2 {
   ^~~~~~~ ~~~~~~~~~
./GenerateCommonCryptoModule.swift:97:19: error: missing argument label 'filePath:' in call
    if fileExists(moduleDirectory) {
                  ^
                  filePath: 
./GenerateCommonCryptoModule.swift:98:21: error: missing argument label 'message:' in call
        reportError("Module directory already exists at \(moduleDirectory).")
                    ^
                    message: 
./GenerateCommonCryptoModule.swift:102:11: error: missing argument label 'path:' in call
if !mkdir(moduleDirectory) {
          ^
          path: 
./GenerateCommonCryptoModule.swift:103:17: error: missing argument label 'message:' in call
    reportError("Failed to create module directory \(moduleDirectory)")
                ^
                message: 
./GenerateCommonCryptoModule.swift:124:17: error: missing argument label 'message:' in call
    reportError("Failed to write module map file to \(moduleMapPath)")
                ^
                message:

**Comment by iosdevzone** [comment]
That's strange... and somewhat embarrassing! Maybe I didn't get the push to CocoaPods 100% correct. Let me take a look.

**Comment by iosdevzone** [comment]
I see what the issue is... I made some errors in the 0.8.1. These were corrected in 0.8.3. Apologies for the inconvenience.

**Comment by SparrowBlaze** [comment]
An old issue now, but seems to be a recurring problem with Xcode 10.2.1 (10E1001):

```
/Users/jamesrobinson/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.10.0-4eef2
Running GenerateCommonCryptoModule
./GenerateCommonCryptoModule.swift:15:34: error: 'characters' is unavailable: Please use String directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^~~~~~~~~~
Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
    public var characters: String { get set }
               ^
```

This appears in my console whenever I try to install via CocoaPods.  Apparently the Swift syntax for the GenerateCommonCryptoModule is wrong now.  I pasted your framework in manually for now, but I'm no expert on frameworks.  I'd like to be able to use CocoaPods here.

Also useful to note, it seems that Xcode has bundled a CommonCrypto map ([mentioned on StackOverflow here](https://stackoverflow.com/a/42852743/3799856)).  From what testing I've done, it works pretty much out of the box, making this script not necessary in modern Xcode. 😄

**Comment by iosdevzone** [comment]
Hi @SparrowBlaze, looks like you need to update the version of IDZSwiftCommonCrypto you're using. Versions from 0.11.3 and up no longer use that script (because, as you correctly mention, it's no longer needed). Perhaps you have a Podfile.lock file that is clamping the version in use? Let me know if you need more assistance.

**Comment by SparrowBlaze** [comment]
Ah, now I see the versions in the Readme.  I always thought that `pod 'PodName'` just pulled the latest one, but I guess not.

**Comment by SparrowBlaze** [comment]
Updated deployment targets and it worked. Thank you.

And great work on this, by the way!  👍

**Comment by iosdevzone** [comment]
When you start a project `pod 'PodName'` will do that, but then CocoaPods creates a `Podfile.lock` which clamps the versions so that you can reproduce that build. I think you need to do a `pod update <podname>` to update to the latest version of a pod...

I hope I have that correct. I would check the CocoaPods docs to be sure ;-)

**Comment by iosdevzone** [comment]
Whoops, messages a little out of order. You're welcome! Glad I was able to help out and the library is useful for you. Finally have a little bit of time to do some clean up, so watch out for version 1.0.0!!!!!!

Have a great morning/day/evening wherever you are!
