### ISSUE TITLE
Support for AES in Galois/Counter Mode?

### ISSUE THREAD

**Issue by bmt22033** [iosdevzone/IDZSwiftCommonCrypto#34]
@iosdevzone any chance that you'll add support for AES in Galois/Counter Mode at some point?  I've been looking for a way to utilize AES GCM in a Swift project and ran across [SwCrypt](https://github.com/soyersoyer/SwCrypt).  It works well enough but was written in Swift 2.x and the author seems to have been MIA for some time now.

**Comment by iosdevzone** [comment]
I am hoping to include all the modes included in PR #29 in the releases over this weekend. I haven't had a chance to check out all the modes but if `CommonCrypto`'s `kCCModeCTR` is what you are looking for then it will be available soon. I have some homework to do myself on GCM so can't be 100% certain that GCM == `kCCModeCTR`.

**Comment by bmt22033** [comment]
@iosdevzone I'm *far* from being an expert at cryptography but I believe that GCM and CTR are different modes of operation.  I'm new to iOS and don't fully understand how SwCrypt calls GCM from Common Crypto but I was using it in a small Swift 2.2 project and it worked.  I ran the source through the migration assistant in XCode 8 but I ultimately ran out of time trying to fix problems and had to fall back to AES CBC using IDZSwiftCommonCrypto.

**Comment by iosdevzone** [comment]
It looks like the routine to implement GCM, `CCCryptorGCM`,  is not strictly publicly available in the sense that the function prototype is not in a public header (see:[StackOverflow: GCM on iOS](http://stackoverflow.com/questions/34855741/how-to-encrypt-using-aes-gcm-on-ios)) . SwCrypt dynamically retrieves the symbol. I am reluctant to add this to the master branch of IDZSwiftCommonCrypto in case it causes apps to be rejected from the app store. I could not find anyone claiming they had an app using SwCrypt accepted, but neither could I find anyone saying they had one rejected.

**Comment by bmt22033** [comment]
@iosdevzone thanks for checking.  It's odd that Apple uses AES/GCM internally but has never exposed it publicly.  I submitted a request to them some time ago asking what their intentions are for AES/GCM and Common Crypto in general regarding usage from Swift but they never responded.

**Comment by iosdevzone** [comment]
@bmt22033 I may still implement it on a separate branch, so I'll leave this open for the moment.

**Comment by iosdevzone** [comment]
This issue has been open for a few years, and it appears that GCM support in CommonCrypto is unlikely to be forthcoming and I am not going to "roll my own", so I am closing it out. It looks like SwCrypt is now back under active development, so on macOS this may be an option, but since it uses `dlopen` I don't think this can be used it an AppStore app.

**Comment by bmt2018** [comment]
Just FYI - it looks like Apple is finally going to give us AES in GCM mode with [CryptoKit](https://developer.apple.com/documentation/cryptokit) in iOS 13.
