### ISSUE TITLE
Trying to update crypto to Swift 3 causing errors

### ISSUE THREAD

**Issue by vinced45** [iosdevzone/IDZSwiftCommonCrypto#38]
Prior to swift 3 I had an extension that converted NSData to Sha1. Now its not working. Here is the pre and post code. Any help would be appreciated. 

`/* Swift 2.2 */
extension Data {

    var sha1: String {
        let digest = Digest(algorithm: .SHA1)
        digest.update(self)
        return hexStringFromArray(digest.final())
    }
}
/* Swift 3.0 */
extension Data {
    
    var sha1: String {
        let digest = Digest(algorithm: .sha1)
        let byteCount: size_t = self.count
        let bytes: UnsafeRawPointer<UInt8> = self.withUnsafeBytes
        digest.update(buffer: bytes, byteCount: byteCount)
        return hexString(fromArray:digest.final())
    }
}`

**Comment by iosdevzone** [comment]
Sorry, the Swift 3.0 changes are a little disruptive and I am lagging on getting the documentation up-to-date.

Here's what your code should look like:
````swift
extension String {
    var sha1: String {
        let digest = Digest(algorithm: .sha1)
        digest.update(string: self)
        return hexString(fromArray: digest.final())
    }
}
````
If this does not solve your problem, please send me more information and reopen this issue.

**Comment by vinced45** [comment]
Thanks. I'll try it tonight and let you know.

**Comment by vinced45** [comment]
I get the following error using your recommendation. "Missing argument for parameter 'byte count' in call. Screenshot included.

![screen shot 2016-09-28 at 11 56 31 am](https://cloud.githubusercontent.com/assets/101286/18923747/2233f326-8573-11e6-8b92-c04673915e4f.png)

**Comment by iosdevzone** [comment]
This is bizarre. I have the exact same code working in a playground here!
I'll try it in a project and get back to you.

**Comment by iosdevzone** [comment]
Oh, I see the problem. I initially thought you were trying to extend `String`, my bad.
Here's what your code would look like for `Data`.

````Swift
extension Data {
    var sha1: String {
        let digest = Digest(algorithm: .sha1)
        digest.update(data: self)
        return hexString(fromArray: digest.final())
    }
}
````

**Comment by vinced45** [comment]
That fixed my problem. Thanks for your help.
