### ISSUE TITLE
Installing IDZSwiftCommonCrypto 0.8.1 using Cocoapods 1.1.0 RC 2

### ISSUE THREAD

**Issue by jaytrixz** [iosdevzone/IDZSwiftCommonCrypto#41]
I'm having this error messages when installing my pods. All my other dependencies are working fine except for IDZSwiftCommonCrypto. This was triggered by updating my pod file. Any idea where I'm having issues?

> -> Installing IDZSwiftCommonCrypto (0.8.1)
>  > Git download
>  > Git download
>      $ /usr/bin/git clone https://github.com/iosdevzone/IDZSwiftCommonCrypto.git
>      /var/folders/gh/dypd9prs2jd7cg7_d59fqqyc0000gn/T/d20161003-29724-z4a2jx
>      --template= --single-branch --depth 1 --branch 0.8.1
>      Cloning into '/var/folders/gh/dypd9prs2jd7cg7_d59fqqyc0000gn/T/d20161003-29724-z4a2jx'...
>      Note: checking out 'af20cf990069900d0ec96d82a4531bec57563637'.
>      
>      You are in 'detached HEAD' state. You can look around, make experimental
>      changes and commit them, and you can discard any commits you make in this
>      state without impacting any branches by performing another checkout.
>      
>      If you want to create a new branch to retain commits you create, you may
>      do so (now or later) by using -b with the checkout command again. Example:
>      
>        git checkout -b <new-branch-name>
>      
>  > Running prepare command
>    $ /bin/bash -c  set -e touch prepare_command.txt echo 'Running
>    prepare_command' pwd echo Running GenerateCommonCryptoModule swift
>    ./GenerateCommonCryptoModule.swift macosx . swift
>    ./GenerateCommonCryptoModule.swift iphonesimulator . swift
>    ./GenerateCommonCryptoModule.swift iphoneos . swift
>    ./GenerateCommonCryptoModule.swift appletvsimulator . swift
>    ./GenerateCommonCryptoModule.swift appletvos . swift
>    ./GenerateCommonCryptoModule.swift watchsimulator . swift
>    ./GenerateCommonCryptoModule.swift watchos .
>    Running prepare_command
>    /Users/administrator/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.8.1-0fe7e
>    Running GenerateCommonCryptoModule
>    ./GenerateCommonCryptoModule.swift:55:1: error: '@noreturn' has been removed; functions that never return should have a return type of 'Never' instead
>    @noreturn func reportError(message: String) {
>    ^~~~~~~~~~
>                                                -> Never 
>    ./GenerateCommonCryptoModule.swift:73:31: error: instance member 'arguments' cannot be used on type 'Process'
>    guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
>                                  ^~~~~~~ ~~~~~~~~~
>    ./GenerateCommonCryptoModule.swift:73:82: error: missing argument label 'message:' in call
>    guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
>                                                                                     ^
>                                                                                     message: 
>    ./GenerateCommonCryptoModule.swift:17:22: error: 'NSPipe' has been renamed to 'Pipe'
>        let outputPipe = NSPipe()
>                         ^~~~~~
>                         Pipe
>    ./GenerateCommonCryptoModule.swift:18:16: error: 'NSTask' has been renamed to 'Process'
>        let task = NSTask()
>                   ^~~~~~
>                   Process
>    ./GenerateCommonCryptoModule.swift:33:12: error: 'NSFileManager' has been renamed to 'FileManager'
>        return NSFileManager.defaultManager().fileExistsAtPath(filePath)
>               ^~~~~~~~~~~~~
>               FileManager
>    ./GenerateCommonCryptoModule.swift:38:13: error: 'NSFileManager' has been renamed to 'FileManager'
>            try NSFileManager.defaultManager().createDirectoryAtPath(path, withIntermediateDirectories: true, attributes: nil)
>                ^~~~~~~~~~~~~
>                FileManager
>    ./GenerateCommonCryptoModule.swift:48:108: error: cannot call value of non-function type 'CharacterSet'
>        return ((s as NSString).stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet()) as String)
>                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
>                                                                                                               
>    ./GenerateCommonCryptoModule.swift:52:37: error: missing argument label 's:' in call
>        return (s == nil) ? nil : (trim(s!) as String)
>                                        ^
>                                        s: 
>    ./GenerateCommonCryptoModule.swift:89:4: error: instance member 'arguments' cannot be used on type 'Process'
>    if Process.arguments.count > 2 {
>       ^~~~~~~ ~~~~~~~~~
>    ./GenerateCommonCryptoModule.swift:97:19: error: missing argument label 'filePath:' in call
>        if fileExists(moduleDirectory) {
>                      ^
>                      filePath: 
>    ./GenerateCommonCryptoModule.swift:98:21: error: missing argument label 'message:' in call
>            reportError("Module directory already exists at \(moduleDirectory).")
>                        ^
>                        message: 
>    ./GenerateCommonCryptoModule.swift:102:11: error: missing argument label 'path:' in call
>    if !mkdir(moduleDirectory) {
>              ^
>              path: 
>    ./GenerateCommonCryptoModule.swift:103:17: error: missing argument label 'message:' in call
>        reportError("Failed to create module directory \(moduleDirectory)")
>                    ^
>                    message: 
>    ./GenerateCommonCryptoModule.swift:124:17: error: missing argument label 'message:' in call
>        reportError("Failed to write module map file to \(moduleMapPath)")
>                    ^
>                    message: 
> [!] /bin/bash -c 
> set -e
> touch prepare_command.txt
> echo 'Running prepare_command'
> pwd
> echo Running GenerateCommonCryptoModule
> swift ./GenerateCommonCryptoModule.swift macosx .
> swift ./GenerateCommonCryptoModule.swift iphonesimulator .
> swift ./GenerateCommonCryptoModule.swift iphoneos .
> swift ./GenerateCommonCryptoModule.swift appletvsimulator .
> swift ./GenerateCommonCryptoModule.swift appletvos .
> swift ./GenerateCommonCryptoModule.swift watchsimulator .
> swift ./GenerateCommonCryptoModule.swift watchos .
> 
> Running prepare_command
> /Users/administrator/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.8.1-0fe7e
> Running GenerateCommonCryptoModule
> ./GenerateCommonCryptoModule.swift:55:1: error: '@noreturn' has been removed; functions that never return should have a return type of 'Never' instead
> @noreturn func reportError(message: String) {
> ^~~~~~~~~~
>                                             -> Never 
> ./GenerateCommonCryptoModule.swift:73:31: error: instance member 'arguments' cannot be used on type 'Process'
> guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
>                               ^~~~~~~ ~~~~~~~~~
> ./GenerateCommonCryptoModule.swift:73:82: error: missing argument label 'message:' in call
> guard let sdk = SDK(rawValue: Process.arguments[1])?.rawValue else { reportError("SDK must be one of \(SDK.all.map { $0.rawValue })") }
>                                                                                  ^
>                                                                                  message: 
> ./GenerateCommonCryptoModule.swift:17:22: error: 'NSPipe' has been renamed to 'Pipe'
>     let outputPipe = NSPipe()
>                      ^~~~~~
>                      Pipe
> ./GenerateCommonCryptoModule.swift:18:16: error: 'NSTask' has been renamed to 'Process'
>     let task = NSTask()
>                ^~~~~~
>                Process
> ./GenerateCommonCryptoModule.swift:33:12: error: 'NSFileManager' has been renamed to 'FileManager'
>     return NSFileManager.defaultManager().fileExistsAtPath(filePath)
>            ^~~~~~~~~~~~~
>            FileManager
> ./GenerateCommonCryptoModule.swift:38:13: error: 'NSFileManager' has been renamed to 'FileManager'
>         try NSFileManager.defaultManager().createDirectoryAtPath(path, withIntermediateDirectories: true, attributes: nil)
>             ^~~~~~~~~~~~~
>             FileManager
> ./GenerateCommonCryptoModule.swift:48:108: error: cannot call value of non-function type 'CharacterSet'
>     return ((s as NSString).stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet()) as String)
>                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
>                                                                                                            
> ./GenerateCommonCryptoModule.swift:52:37: error: missing argument label 's:' in call
>     return (s == nil) ? nil : (trim(s!) as String)
>                                     ^
>                                     s: 
> ./GenerateCommonCryptoModule.swift:89:4: error: instance member 'arguments' cannot be used on type 'Process'
> if Process.arguments.count > 2 {
>    ^~~~~~~ ~~~~~~~~~
> ./GenerateCommonCryptoModule.swift:97:19: error: missing argument label 'filePath:' in call
>     if fileExists(moduleDirectory) {
>                   ^
>                   filePath: 
> ./GenerateCommonCryptoModule.swift:98:21: error: missing argument label 'message:' in call
>         reportError("Module directory already exists at \(moduleDirectory).")
>                     ^
>                     message: 
> ./GenerateCommonCryptoModule.swift:102:11: error: missing argument label 'path:' in call
> if !mkdir(moduleDirectory) {
>           ^
>           path: 
> ./GenerateCommonCryptoModule.swift:103:17: error: missing argument label 'message:' in call
>     reportError("Failed to create module directory \(moduleDirectory)")
>                 ^
>                 message: 
> ./GenerateCommonCryptoModule.swift:124:17: error: missing argument label 'message:' in call
>     reportError("Failed to write module map file to \(moduleMapPath)")
>                 ^
>                 message: 
> 
> 
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/executable.rb:69:in `execute_command'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/executable.rb:27:in `block in executable'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:157:in `each'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:181:in `call'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader.rb:42:in `download'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:85:in `titled_section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:313:in `each'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:313:in `install_pod_sources'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:157:in `download_dependencies'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:111:in `install!'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
> /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'

**Comment by iosdevzone** [comment]
Hi @jaytrixz, looks like you are using Xcode 8.0 with Swift 3.0. You will need version 0.9.0 to do this. Update your podfile with `~>0.9.0` as the version.

**Comment by jaytrixz** [comment]
Thank you. Please close this issue. Guess I didn't see the logs clearly.

**Comment by jaytrixz** [comment]
I am getting Swift Compiler Error issues. Please see attached screenshot
![untitled](https://cloud.githubusercontent.com/assets/1453309/19370785/79453926-91e0-11e6-9eaf-ae9a6d925c5f.png)

**Comment by iosdevzone** [comment]
It looks like you opened a project using Swift 3.0 in Xcode 7.x. Please ensure you use Xcode 8.x if you are using Swift 3.0.

**Comment by jaytrixz** [comment]
This is getting frustrating because I am using Xcode 8 and Swift 2.3 and IDZSwiftCommonCrypto v0.8.3 yet I keep on getting this kind of error. When I try to Edit > Convert > To Current Swift Syntax, Xcode tells me that everything in my project including my pods are already on Swift 2.3

**Comment by iosdevzone** [comment]
The code in your screenshot is *not* from IDZSwiftCommonCrypto 0.8.3 which is the version you should be using for Xcode 8.x and Swift 2.3, it's from 0.9.0 which is Swift 3.0. Please ensure the version in your Podfile is 0.8.3. The clue is the `open` qualifier on the class; this is Swift 3.0 syntax. 

You should not use  **Edit > Convert > To Current Swift Syntax** on IDZSwiftCommonCrypto you should pull the current version from GitHub

**Comment by Samback** [comment]
This error could be fired in case if you have a multiple number of Xcode versions setup on your machine. You need to check, is it correct selected now.
sudo xcode-select -s "/Users/..../..../Xcode.app/Contents/Developer"

**Comment by iosdevzone** [comment]
@Samback this is an excellent point. Thanks for drawing it to my attention. I notice in all of the discussion with the OP I did not think of checking this.
