### ISSUE TITLE
Error 'Undefined symbols for architecture arm64'

### ISSUE THREAD

**Issue by Adarkas2302** [iosdevzone/IDZSwiftCommonCrypto#42]
Hi, i am getting the following errors while compiling my project.

Undefined symbols for architecture arm64:
  "IDZSwiftCommonCrypto.Cryptor.__allocating_init (operation : IDZSwiftCommonCrypto.StreamCryptor.Operation, algorithm : IDZSwiftCommonCrypto.StreamCryptor.Algorithm, options : IDZSwiftCommonCrypto.StreamCryptor.Options, keyBuffer : Swift.UnsafeRawPointer, keyByteCount : Swift.Int, ivBuffer : Swift.UnsafeRawPointer) -> IDZSwiftCommonCrypto.Cryptor", referenced from:
      G6Mobil.ViewController.DeCrypt ([Swift.UInt8], key : [Swift.UInt8]) -> [Swift.UInt8] in VCLogin.o
      G6Mobil.ViewController.EnCrypt ([Swift.UInt8], key : [Swift.UInt8]) -> [Swift.UInt8] in VCLogin.o
  "(extension in IDZSwiftCommonCrypto):IDZSwiftCommonCrypto.Updateable.update (byteArray : [Swift.UInt8]) -> A?", referenced from:
      G6Mobil.ViewController.DeCrypt ([Swift.UInt8], key : [Swift.UInt8]) -> [Swift.UInt8] in VCLogin.o
      G6Mobil.ViewController.EnCrypt ([Swift.UInt8], key : [Swift.UInt8]) -> [Swift.UInt8] in VCLogin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

My code for these two functions look like this.

```
func DeCrypt(_ crypted: [UInt8], key: [UInt8]) -> [UInt8] {
  let IVArray: [UInt8] = [0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00]
        let cryptor = Cryptor(operation: .decrypt, algorithm: .aes, options: .ECBMode, keyBuffer: key, keyByteCount: key.count, ivBuffer: IVArray)
        let decrypted = cryptor.update(byteArray: crypted)?.final()
        return decrypted!
 }

func EnCrypt(_ decrypted: [UInt8], key: [UInt8]) -> [UInt8] {
        let IVArray: [UInt8] = [0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00]
        let cryptor = Cryptor(operation: .encrypt, algorithm: .aes, options: .ECBMode, keyBuffer: key, keyByteCount: key.count, ivBuffer: IVArray)
        let encrypted = cryptor.update(byteArray: decrypted)?.final()
        return encrypted!
 }
 ```  

I have IDZSwiftCommonCrypt version 0.9.0 and i installed it via cocoapods version '1.1.0.rc.2'.
Code worked fine previous to the changes caused by swift 3.0.

Can you see what i am doing wrong?

**Comment by iosdevzone** [comment]
Well, there's nothing wrong with your code, so the issue is somewhere in the build; either (1) some of Xcode's intermediate files are invalid or incomplete or (2) some build setting is incorrect. 
To try to eliminate (1) try doing a clean build  **Product -> Clean**, if that does not solve the problem try deleting your DerivedData folder `rm -rf ~/Library/Developer/Xcode/DerivedData`. If neither of these solve the problem then (2) is most likely the issue. The most likely build setting that would cause this issue is the **Architectures** setting in the **Pods** subproject make sure it is set to **Standard Architectures**.

Hope this helps.

**Comment by Adarkas2302** [comment]
oh wow thanks. I thought of everything but not to check the settings in the Pods subproject. Thanks, you helped me a lot.

**Comment by iosdevzone** [comment]
You're welcome. Glad you got things working again!

**Comment by Adarkas2302** [comment]
Yeah, never thought Swift 3.0 would be such a hassle. ;)
