### ISSUE TITLE
USA Export Regulations reference

### ISSUE THREAD

**Issue by lferro9000** [iosdevzone/IDZSwiftCommonCrypto#46]
It may be of use to have some references regarding the export regulations regarding to crypto in the USA as Apple enforces it to all markets:

https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States

https://www.bis.doc.gov/index.php/policy-guidance/encryption/registration

The process was moved to online, allowing quick registration nowadays.

**Comment by bmt22033** [comment]
It's my understanding that as of September 20, encryption registrations are no longer required:

http://www.bis.doc.gov/InformationSecurity2016-updates

**Comment by iosdevzone** [comment]
Folks, I am not a lawyer and the rules on cryptography vary as time moves on and by jurisdiction. If you use this library in your app you need to follow the same rules as you would if you were using CommonCrypto directly. The source code of this repository contains no cryptographic algorithms.

I do not think providing links to a particular jurisdiction's rules is appropriate.
