### ISSUE TITLE
New "update" usage? Please renew your readme.md file

### ISSUE THREAD

**Issue by rmvz3** [iosdevzone/IDZSwiftCommonCrypto#47]
Hi. I'm trying to do a single string DES encryption but it seems the documentation isn't updated to current status (I'm talking about Swift 3 version)

When I try:
`var cipherText = cryptor.update(plainText)?.final()`

I get an unknown method error. I see the `update` function is modified. Can you please add its new usage?

thanks

**Comment by iosdevzone** [comment]
Apologies for the lag in documentation.

In keeping with the Apple's recommendations for API naming conventions update now has a parameter label. Currently the label depends on the type of the argument (I'm not that happy with this; in the next release I'll try to come up with something better). For the moment, depending on the type of your `plainText` variable you should use

````swift
var cipherText = cryptor.update(data: plainText)?.final() // if plainText is Data
// **or**
var cipherText = cryptor.update(byteArray: plainText)?.final() // if plainText is [UInt8]
// **or**
var cipherText = cryptor.update(data: plainText)?.final() // if plainText is String
````
Hope this makes things clearer.
