### ISSUE TITLE
Xcode 8.1 compatibility?

### ISSUE THREAD

**Issue by leobouilloux** [iosdevzone/IDZSwiftCommonCrypto#48]
Hello, I updated to Xcode 8.1 and I can't get my project to run now.

Here is a screenshot with the 2 errors involved:
<img width="466" alt="screen shot 2016-10-31 at 10 02 17" src="https://cloud.githubusercontent.com/assets/1726316/19849026/27005f82-9f51-11e6-9c49-df9709fd95df.png">

Is there any quick fix like changing `/iPhoneOS10.0.sdk/` by `/iPhoneOS10.1.sdk/` ?

Hope you can help me and cheers for the good work!

**Comment by nyekimov** [comment]
the path should be changed to iPhoneOS10.1.sdk, anyone who needs it asap, can change manually.

**Comment by leobouilloux** [comment]
Okay, thank you very much! I confirm it's working.
