### ISSUE TITLE
Getting Error  on Decrypt

### ISSUE THREAD

**Issue by kamalupasena** [iosdevzone/IDZSwiftCommonCrypto#50]
Hi i am using the decrypting as follows 

```
let cryptor =  Cryptor(operation: .Decrypt, algorithm: .AES, mode: .CTR, padding: .NoPadding, key: keyArray, iv: ivDecodeData!)
        
       let decryptedPart =  cryptor.update(encrptedPart)?.final()
```

but when  i am doing this i am getting an error at this methode from the lib

```
public func getOutputLength(inputByteCount : Int, isFinal : Bool = false) -> Int
    {
        return CCCryptorGetOutputLength(context.memory, inputByteCount, isFinal)
    }
```

can you tell me what i am doing wrong there i am using `Array<UInt8>()` for both key and  iV 
key has 16 bytes 

and i am trying decrpyt a file save in side the application

**Comment by iosdevzone** [comment]
Apologies for the delay in responding. I suspect you have figured out your error by now, but if not; the most likely cause is that, since you specified no padding, that your input buffer is not an integral number of blocks.
