### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by AllenEzailLai** [iosdevzone/IDZSwiftCommonCrypto#51]
When I update XCode 8.1 and re-build my project I get errors:

`Header '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/usr/include/CommonCrypto//CommonCrypto.h' not found`
AND
`Could not build Objective-C module 'CommonCrypto'`

thank you for help

**Comment by Tibb** [comment]
You just updated Xcode and your iOS SDK: the error comes from this module.map file where the path isn't valid anymore.

Just replace 
    `iPhoneSimulator10.0.sdk`
with
   `iPhoneSimulator10.1.sdk`

This is temporary solution, but it worked for me ;)

**Comment by CBeloch** [comment]
These lines in `module.map` are generated during the build of the framework.
When you build it together with your app you should be fine

**Comment by Tibb** [comment]
Yes I know @CBeloch.. It's working fine on the Xcode side. But building it via Fastlane generates this error (using `gym`).
My target and project are set to the latest sdk (10.1).
My `gym` config is also explicitly set to "`iphoneos10.1`".
Basically every configuration parameter relative to the sdk should be set to 10.1.

I also clean pod cache and derived data before build.
Still getting this wrong 10.0 path element..

**Comment by Tibb** [comment]
Well well well, I deleted the IDZCommonCrypto pod, then reinstall it, and... it works!
There was probably some remaining artifacts of the previous Xcode version somewhere.
Hope it helps

**Comment by AllenEzailLai** [comment]
it works~!! thank u~

**Comment by Tibb** [comment]
And.... Same error again after the last Xcode update. (sdk 10.1 instead of 10.2 in the module.map path).

I tried:
- clean project
- clean derived data
- uninstall/reinstall the pod
- relaunch Xcode

None of this solution worked.

The only _temporary_ working solution so far is a manual modification of the module.map file path.

What am I missing?

**Comment by iosdevzone** [comment]
The module.map is generated during the build if (and only if) one does not exist.

How it is produced depends on whether your are using Cocoapods or the Xcode workspace. In the Cocoapods case a `prepare_command` script is created by the podspec and run after the pod is installed. In the Xcode workspace case, the script is run by a **Run Script** build phase. All these scripts do is invoke `GenerateCommonCryptoModule.swift` a number of times to generate the platform-specific `module.map`s. The `GenerateCommonCryptoModule.swift` script determines the correct SDK version using `xcrun --sdk <sdk_name> --show-sdk-path`.

When you upgrade Xcode you must do the following:
• use `sudo xcode-select -p <path_to_new_xcode>` to ensure that `xcrun` will find the correct SDK
• perform a completely clean build, that is, remove all generated files including the `module.map` files.

If you are constantly running into the problem of SDK mismatches, you are failing to one of the above steps.

Hope this explanation helps you make your Xcode upgrades smoother.

**Comment by CBeloch** [comment]
The map generated in the build process has a problem when your path contains spaces.
I made a pull request already that fixes this issue: #52

**Comment by Tibb** [comment]
Thanks a lot for the help guys.

@iosdevzone I performed your recommend steps:

- `xcode-select -p` returns `/Applications/Xcode.app/Contents/Developer` which seems to be ok. Going a bit further -> `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk`

_This is my one and only instance of Xcode.app
I checked the SDK info.plist: 10.2_

- I also performed a completely clean build: I removed every generated resources from IDZ including the `module.map` (basically the whole generated framework)

Unfortunately, I still got the same error :(

Here is my generated module.map content:

```
module CommonCrypto [system] {
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/CommonCrypto//CommonCrypto.h"
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/include/CommonCrypto//CommonRandom.h"
  export *
}
```

Am I the only one facing this issue?

**Comment by iosdevzone** [comment]
This very strange. Use the command 
`xcrun --sdk iphonesimulator --show-sdk-path` 
and let me know the result.

**Comment by Tibb** [comment]
Here's the result:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk` .... very strange indeed.

It doesn't make sense for me, and after having checked every configuration parameter, file, resource, etc, I'm running out of solution.

**Comment by iosdevzone** [comment]
There's only a few possibilities left:
• perhaps you are not really deleting the `module.map` files, or perhaps the wrong ones,
• perhaps you inadvertently checked the module.map files into source code control and something in your build is retrieving them from there,
• there could be something in your build that is aliasing `xcrun` or changing your `PATH` such that the answer you are getting on the command line is different from the one the script sees during a build.
I have a test repository I use to make sure the project builds with CocoaPods [IDZSwiftCommonCryptoCocoaPodsTest](https://github.com/iosdevzone/IDZSwiftCommonCryptoCocoaPodsTest) you could try that and ensure that it builds.

**Comment by Tibb** [comment]
Thanks a lot for your help, I'll check your example and your suggestions. I'll let you know if (I hope) find the problem.

**Comment by iosdevzone** [comment]
You're welcome! I hope you get to bottom of it. Let me know if you need any more help.

**Comment by Tibb** [comment]
I tried your Test project -> same path error

Terminal:
`/usr/bin/xcrun --sdk iphoneos --show-sdk-path`
> `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk`

`/usr/bin/xcrun --sdk iphonesimulator --show-sdk-path`
> `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk`


I'm desperate...

**Comment by Tibb** [comment]
Since I was not able to find the source of this error (I even completely reinstalled Xcode), I decided to remove your lib and make the encryption layer by myself.
Thanks again for your precious help and sorry that we didn't managed to figure this out.

**Comment by iosdevzone** [comment]
I'm really sorry we couldn't get to the bottom of this. Remember you can always use the project directly (without CocoaPods) this will make it easier to see build logs. However you decide to proceed the best of luck with your project and thanks for all the time you spent trying to get to the bottom of the issue. Happy New Year!

**Comment by Tibb** [comment]
Thank you @iosdevzone and Happy New Year!
