### ISSUE TITLE
Can't install using cocoa pods (0.9.0)

### ISSUE THREAD

**Issue by SnitramDev** [iosdevzone/IDZSwiftCommonCrypto#54]
I've tried: 
pod 'IDZSwiftCommonCrypto', '~> 0.9.0'

> [!] Unable to satisfy the following requirements:
> 
> - `IDZSwiftCommonCrypto (~> 0.9.0)` required by `Podfile`
> 
> Specs satisfying the `IDZSwiftCommonCrypto (~> 0.9.0)` dependency were found, but they required a higher minimum deployment target.

When trying to install 1.0.0
pod 'IDZSwiftCommonCrypto', '~> 1.0'

> None of your spec sources contain a spec satisfying the dependency: `IDZSwiftCommonCrypto (~> 1.0)`.

**Comment by iosdevzone** [comment]
The issue is your deployment target in Xcode. The 0.9.0 podspec has a minimum deployment target of iOS 9.3. This is because I have limited access to device to test on and do not like to ship code I cannot test.
After installing the pod you can manually set the minimum deployment target to an earlier version.

**Comment by SnitramDev** [comment]
Thank you. Please understand that I am *not able* to build my project after I change it back to 9.0. Could you please change it so I can use the library? Let me test it out for you...

Thanks.

**Comment by iosdevzone** [comment]
Why are you not able to build your project? As long as you remember to change the deployment target in your main project and the Pods project there should be no problem. Once you have done `pod install` the build does not look at the Podfile again.

**Comment by SnitramDev** [comment]
I throws an error when building the project... Installation via cocoa pods went fine. Then I changed the deployment target back to 9.0, and while trying to build, xcode immediately complained about the library not compiling:

> Module file's minimum deployment target is ios9.3 v9.3: /Users/me/Library/Developer/Xcode/DerivedData/TestApp-ezhpwpnsaizavsgjnkjkyksxipox/Build/Products/Debug-iphoneos/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto.framework/Modules/IDZSwiftCommonCrypto.swiftmodule/arm64.swiftmodule

**Comment by iosdevzone** [comment]
This means you did not change the deployment target of the Pod project; that is, you changed your main project's deployment target but did not do the `Pods` project.

**Comment by iosdevzone** [comment]
Apologies it took so long to provide more than a workaround for this issue.
I've just pushed v0.9.1 to CocoaPods. This has an iOS deployment version of 9.0. See also #62
