### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by seanscal** [iosdevzone/IDZSwiftCommonCrypto#6]
```
[!] Unable to satisfy the following requirements:

- `IDZSwiftCommonCrypto` required by `Podfile`

Specs satisfying the `IDZSwiftCommonCrypto` dependency were found, but they required a higher minimum deployment target.
```

podfile:

```
platform :ios, '8.3'
use_frameworks!

target 'PasswordRecovery' do
    pod 'IDZSwiftCommonCrypto'
end

target 'PasswordRecoveryTests' do

end

```

Any help is appreciated!

**Comment by iosdevzone** [comment]
OK, looks like I was a bit aggressive with the required version in the pod spec. Will roll  it back, run some tests and get back to you.
Sorry for the inconvenience!

**Comment by iosdevzone** [comment]
This should be fixed now. Version 0.6.6 rolls back the iOS deployment target to 8.0. You will still need to be using Xcode 7.1 to build though!

**Comment by iosdevzone** [comment]
@seanscal Did this fix the problem for you? I would like to close out this issue.

**Comment by seanscal** [comment]
good to go, thanks!
