### ISSUE TITLE
Cannot open: No such file or directory: IDZSwiftCommonCrypto_vers.gcda

### ISSUE THREAD

**Issue by danielideriba** [iosdevzone/IDZSwiftCommonCrypto#60]
Hi everyone! 

I got a issue when I try to run my project with IDZSwiftCommonCrypto. I use to be run on debug mode suddenly occur this error: "/Users/myuser/Library/Developer/Xcode/DerivedData/IDZSwiftCommonCrypto-adhhsvuugffztcdubqosnyysjjma/Build/Intermediates/IDZSwiftCommonCrypto.build/Release-iphoneos/IDZSwiftCommonCrypto (iOS).build/Objects-normal/armv7/IDZSwiftCommonCrypto_vers.gcda: cannot open: No such file or directory"

Do you know how to solve this issue? 
Best regards

**Comment by iosdevzone** [comment]
Hi Daniel,
In debug mode IDZSwiftCommonCrypto generates coverage data, this is used to ensure the test coverage is good. It looks like after switching to release mode Xcode is confused and is still looking for one of the files containing coverage data (I'm not sure why). 
You could try the follow:

(1) Clean your project (**Product > Clean**) and rebuild.

Sometime Xcode doesn't correctly rebuild all the necessary files after configuration changes. This sometimes solves the problem.

If this does not work, you could try:
(2) Delete Xcode derived data `rm -rf ~/Library/Developer/Xcode/DerivedData`

Xcode caches data in this directory. Sometimes it appears not to realize that some of the files are invalid.

If neither (1) nor (2) solves you problem please let me know. In addition to the information you already provided please also tell me:
* What version of Xcode you are using
* How you are integrating IDZSwiftCommonCrypto (i.e. CocoaPods, Carthage, or direct use of Project).

Hopefully I can help you out,
Danny

**Comment by iosdevzone** [comment]
Closing issue due to lack of response.
