### ISSUE TITLE
TripleDES: fatal error: FATAL_ERROR: Invalid key size

### ISSUE THREAD

**Issue by ababatuwe** [iosdevzone/IDZSwiftCommonCrypto#61]
Hi everyone!

I got an issue when I try to encrypt using TripleDES. I wrote the following function to encrypt data before it's transmitted.
`    
 func encrypt(_ data: String) -> [UInt8]? {
        let key = arrayFrom(hexString: "2b7e151628aed2a6abf7158809cf4f3c")
        let blockSize = Cryptor.Algorithm.tripleDES.blockSize()
        let plainText = zeroPad(string: data, blockSize: blockSize)
        
        let cryptor = Cryptor(operation: .encrypt, algorithm: .tripleDES, options: [.ECBMode], keyBuffer: key, keyByteCount: key.count, ivBuffer: "")
        let cipherText = cryptor.update(byteArray: plainText)?.final()
        
        return cipherText
    }`

While I was trying to test it out, I kept running into the following error: 

"fatal error: FATAL_ERROR: Invalid key size.: file /Users/admin/Desktop/Hyperwire/Pods/IDZSwiftCommonCrypto/IDZSwiftCommonCrypto/StreamCryptor.swift, line 381"

Do you know how to solve this issue?
Thanks for the help.

**Comment by iosdevzone** [comment]
Hi there,
CommonCrypto only documents supporting a 192 bit key size (168 effective bits). 
I wondered if, perhaps, this was just a documentation issue, so I tried disabling the key size validity check, but then `CCCryptorCreate` fails.

But all is not lost. The 192 bit key is formed by concatenating three individual 64-bit keys K<sub>1</sub>|K<sub>2</sub>|K<sub>3</sub>. The 128 bit key uses only two 64-bit keys K<sub>1</sub>|K<sub>2</sub>; it reuses K<sub>1</sub> for the third round. This means you can expand the 128 bit key into 192 bit key like this: expand(K<sub>1</sub>|K<sub>2</sub>) -> K<sub>1</sub>|K<sub>2</sub>|K<sub>1</sub>

In your code that would look something like this:
````swift
func encrypt(_ data: String) -> [UInt8]? {
    let key128 = arrayFrom(hexString: "2b7e151628aed2a6abf7158809cf4f3c")
    let key192 = key128 + key128[0...7]
    let blockSize = Cryptor.Algorithm.tripleDES.blockSize()
    let plainText = zeroPad(string: data, blockSize: blockSize)
    
    let cryptor = Cryptor(operation: .encrypt, algorithm: .tripleDES, options: [.ECBMode], keyBuffer: key192, keyByteCount: key192.count, ivBuffer: "")
    let cipherText = cryptor.update(byteArray: plainText)?.final()
    
    return cipherText
}
````
Let me know if this fixes your issue so I can close this issue. 
Thanks,
Danny

**Comment by iosdevzone** [comment]
Closing issue due to lack of response.

**Comment by ababatuwe** [comment]
@iosdevzone the solution worked. Thank you!

**Comment by iosdevzone** [comment]
@ababatuwe Excellent! Glad it worked for you!

**Comment by funmania** [comment]
I am still getting the invalid key size crash, below is how i am using it.
`
func tripleDES() {
        let keyStr = "xxxxxxxxxxxxxxxxxxxx"
        let data = keyStr.data(using: .utf8)!
        let hexString = data.map{ String(format:"%02x", $0) }.joined()
        let key128 = arrayFrom(hexString: hexString)
        let key192 = key128 + key128[0...7]
        let blockSize = Cryptor.Algorithm.tripleDES.blockSize()
        let plainText = zeroPad(string: "test", blockSize: blockSize)
        
        let cryptor = Cryptor(operation: .encrypt, algorithm: .tripleDES, options: [.ECBMode], keyBuffer: key192, keyByteCount: key192.count, ivBuffer: "")
        let cipherText = cryptor.update(byteArray: plainText)?.final()
    }
`
