### ISSUE TITLE
iOS minimum deployment target

### ISSUE THREAD

**Issue by serieuxchat** [iosdevzone/IDZSwiftCommonCrypto#62]
Is it essential that the minimum deployment target is 9.3?
(We still need to support 9.0, so the pod won't install for us)

**Comment by iosdevzone** [comment]
Apologies, this was initially because I did not have a suitable device on which to test 9.0.
It's been on my todo list to push a new CocoaPod with a more "forgiving" deployment version. 
I've just pushed version 0.9.1 to CocoaPods -- this has a iOS deployment target of 9.0.

**Comment by serieuxchat** [comment]
Thank you so much! :-)
