### ISSUE TITLE
Problem with Decrypt a Text

### ISSUE THREAD

**Issue by EfrainPerez** [iosdevzone/IDZSwiftCommonCrypto#65]
Hi, I have a problem with decrypt a Text. I'm sending to the function a String with the cryptedText, not the Array of bytes, and it can not get the original plainText. 
Do it exist a way to get the original array of bytes?
## Here is my code, with the function that receive a String
```
    private func encrypt(plaintext: String)->String?{
        var cipherText: String! = nil
        if plaintext != ""{
            let cryptor = Cryptor(operation:.encrypt, algorithm:.aes, options:.PKCS7Padding, key: self.key, iv: self.iv)
            let array = cryptor.update(string:plaintext)?.final()
            cipherText = NSData(bytes: array, length: (array?.count)!).base64EncodedString(options: [])
        }
        return cipherText
    }
    
    
    private func decrypt(cryptedText :String)->String?{
        var originalText : String! = nil
        if cryptedText != ""{
            let cryptor = Cryptor(operation:.decrypt, algorithm:.aes, options:.PKCS7Padding, key: self.key, iv: self.iv)
            let array = cryptor.update(string: cryptedText)?.final()
            originalText = array?.reduce("") { $0 + String(UnicodeScalar($1))}
        
        }
        return originalText
    }
    
```
## Here is my code, with the function that receive a[Uint8] (and it works)

```
private func encryptText(plaintext: String)->[UInt8]?{
        var cipherText: [UInt8]! = nil
        if plaintext != ""{
            let cryptor = Cryptor(operation:.encrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv: self.iv)
            cipherText = cryptor.update(string:plaintext)?.final()
        }
        return cipherText
        
    }
    
    private func decryptText(cipherText textToDecrypt: [UInt8]?)->[UInt8]?{
        var decryptedText: [UInt8]! = nil
        if textToDecrypt != nil{
            let cryptor = Cryptor(operation:.decrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv: self.iv)
            decryptedText = cryptor.update(byteArray:textToDecrypt!)?.final()
        }
        return decryptedText
    }

```

Thanks if you can help I will appreciate

**Comment by iosdevzone** [comment]
Hi There,
1) In your `decrypt` routine you need to base64decode before passing it decrypt.
2) When you recreate the String from the decrypted buffer you need to use UTF8. 

It should look something like this:
````swift
    public func decrypt(cryptedText :String)->String?{
        var originalText : String! = nil
        if cryptedText != ""{
            guard let cipherText = NSData(base64Encoded: cryptedText, options: []) else { return nil }
            let cryptor = Cryptor(operation:.decrypt, algorithm:.aes, options:.PKCS7Padding, key: self.key, iv: self.iv)
            guard let array = cryptor.update(data: cipherText as Data)?.final() else { return nil }
            originalText = String(bytes: array, encoding: .utf8)!
        }
        return originalText
    }
````
You should update the two `guard` statements to take whatever error handling action is appropriate for you app.

Hope this helps!

**Comment by EfrainPerez** [comment]
**Hi Thank you for your time. I can fix it :D
Here is the code that fix it the last one **

`    private func  encriptText(plaintext : String) ->String{
        let data = plaintext.data(using: .utf8)
        let cryptor = Cryptor(operation:.encrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv: self.iv)
        let bytes = cryptor.update(data: data!)?.final()
        let encData = NSData(bytes: bytes, length: Int((bytes?.count)!))
        let base64String: String = encData.base64EncodedString(options: .init(rawValue: 0))
        let result = String(base64String)
        print(result!)
        return result!
    }
    
    private func decryptText(plaintext: String) ->String{
        let data = NSData(base64Encoded: plaintext, options: .init(rawValue: 0))
        let cryptor = Cryptor(operation:.decrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv: self.iv)
        let bytes = cryptor.update(data: data as! Data)?.final()
        let decData = NSData(bytes: bytes, length: Int((bytes?.count)!))
        var result: NSString!
        result = NSString(data: decData as Data, encoding: String.Encoding.utf8.rawValue)
        print(result, (result as String).characters.count)
        if  ((result) != nil){
            return result as String
        }
        return "No decrypted"
        
    }`

**Comment by EfrainPerez** [comment]
# **Hi, I could fix it and thank you for your time!!! :D**

**Here is the code**

```
    private func  encriptText(plaintext : String) ->String{
        let data = plaintext.data(using: .utf8)
        let cryptor = Cryptor(operation:.encrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv: self.iv)
        let bytes = cryptor.update(data: data!)?.final()
        let encData = NSData(bytes: bytes, length: Int((bytes?.count)!))
        let base64String: String = encData.base64EncodedString(options: .init(rawValue: 0))
        let result = String(base64String)
        print(result!)
        return result!
    }
```

```
    private func decryptText(plaintext: String) ->String{
        let data = NSData(base64Encoded: plaintext, options: .init(rawValue: 0))
        let cryptor = Cryptor(operation:.decrypt, algorithm:.aes, options:.PKCS7Padding, key:key, iv: self.iv)
        let bytes = cryptor.update(data: data as! Data)?.final()
        let decData = NSData(bytes: bytes, length: Int((bytes?.count)!))
        var result: NSString!
        result = NSString(data: decData as Data, encoding: String.Encoding.utf8.rawValue)
        print(result, (result as String).characters.count)
        if  ((result) != nil){
            return result as String
        }
        return "No decrypted"
        
    }
```
