### ISSUE TITLE
Use pod_target_xcconfig instead of xcconfig in the podspec

### ISSUE THREAD

**Issue by brindy** [iosdevzone/IDZSwiftCommonCrypto#69]
Hello,

This project currently causes a warning to be shown running `pod install` related to SWIFT_VERSION.

There is some discussion of it here: 
https://github.com/CocoaPods/CocoaPods/issues/5952#issuecomment-264738739

The solution is apparently to use pod_target_xcconfig instead of xcconfig in the podspec.

Thanks in advance.

**Comment by iosdevzone** [comment]
This was solved in PR #63.
