### ISSUE TITLE
PKCS5Padding is not supporting 

### ISSUE THREAD

**Issue by dhanasekarkannan** [iosdevzone/IDZSwiftCommonCrypto#72]
how to achieve  tripledes hash with pkcs5 padding -  but PKCS5 is not supporting.

**Comment by iosdevzone** [comment]
Sorry for the delay in getting back to you. This library only supports algorithms supported by CommonCrypto. Since CommonCrypto does not support PKCS5 I don't expect to support it anytime soon.
