### ISSUE TITLE
Swift 4.0 or Swift 3.2 support

### ISSUE THREAD

**Issue by matepapp** [iosdevzone/IDZSwiftCommonCrypto#73]
Is the library going to support Swift 3.2 or Swift 4.0?

**Comment by scha00** [comment]
Is it normal that the current library build fails with Swift 4.0? 
I'm trying to figure out how to compile the library with Swift 3.2 assuming the problem only exists in Swift 4.

**Comment by iosdevzone** [comment]
PR #75 will track Swift 3.2 changes. Swift 4 updates will come after that is merged.

**Comment by Jcarto** [comment]
I am getting the following error compiling my App...
Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Users/john/Documents/Aurora/IDZSwiftCommonCrypto.framework/Modules/IDZSwiftCommonCrypto.swiftmodule/x86_64.swiftmodule

No luck getting it to compile so far...
I am using carthage and have updated with that, but still nothing...

**Comment by iosdevzone** [comment]
@Jcarto -- Looks like you have multiple versions of Xcode installed. Make sure `xcode-select -p` is pointing to the correct one!

**Comment by Jcarto** [comment]
Pretty sure I only have Xcode 9 installed, it just upgraded from 8.
I don't know how to verify this?

**Comment by homocogitum** [comment]
@Jcarto I had such issue when I compliled cocoapods project with one version of xcode, and then tried to launch it in another version of xcode (with another version of swift). Try cleaning your project and building cocoapods project again.

**Comment by iosdevzone** [comment]
Version 0.10.0 now supports Swift 4.0 so closing this now. 
@Jcarto If you are still seeing errors, please open a separate issue and I'll try to help you out.

**Comment by Jcarto** [comment]
Thank you I am now able to function. Appreciate your help!.
