### ISSUE TITLE
carthage update infinite loop 

### ISSUE THREAD

**Issue by mateo666** [iosdevzone/IDZSwiftCommonCrypto#77]
dont know if i should post this here or on carthage but when i do 
carthage update

it blocks right after *** Fetching IDZSwiftCommonCrypto
and my laptop wants to take off 

have to ctrl-c to stop the process

??

**Comment by iosdevzone** [comment]
Hmm, not sure what I could be doing to cause that, but I'll take a look. Might be a few days before I get a chance.
Might be no harm to see if anyone on the Carthage side can help.

**Comment by iosdevzone** [comment]
@mateo666 To help with this would you mind telling me the following:
• macOS version,
• Xcode version,
• carthage version?

**Comment by mateo666** [comment]
sorry i dont think it was related to this library.
it would stop even if i removed it.

**Comment by iosdevzone** [comment]
No worries, hope you find a solution soon!
