### ISSUE TITLE
Unable to compile with Xcode 9.1

### ISSUE THREAD

**Issue by csotiriou** [iosdevzone/IDZSwiftCommonCrypto#78]
It seems that the "dummy" CommonCrypto module is being created for iOS 11 and not 11.1, which is the base sdk for Xcode 9.1

My app fails to compile with this message:

```
Header '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/CommonCrypto//CommonCrypto.h' not found
```

and the module map generated looks like this:

```
module CommonCrypto [system] {
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/CommonCrypto//CommonCrypto.h"
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/CommonCrypto//CommonRandom.h"
  export *
}

```

...which indicates that the library - generated module map searches in the old sdk.

**Comment by iosdevzone** [comment]
The build does not generate the module maps if they are already present. Is it possible that you have module maps from a build with a previous version of Xcode still around?

The script that generates the module maps uses the command:
`xcrun --sdk iphoneos --show-sdk-version`
to figure out the appropriate SDK version to use. What does this command output on your system?

**Comment by csotiriou** [comment]
By typing this command, I get the response "11.1", which is correct.

I tried deleting the pods directory, the Podfile.lock, and the DerivedData altogether. Then I made a `pod install`, and the same thing happened, I get the wrong CommonCrypto module.

I tried downloading the entire library repo from GitHub, and then running the Xcode project which seemed to produce the correct results.

I figure that when downloading it as a dependency, the script that runs there fails to determine the correct SDK path.

What is the step that actually generates the module map inside the dependency, while it is installed via Cocoapods? Maybe I can tackle with it a little bit and try to debug it.

I should note that I have multiple Xcode's installed, but the current one is in `/Applications/Xcode.app` and I can verify that xcode-select points to it, which is Xcode 9.1.

**Comment by iosdevzone** [comment]
Sorry this is still causing problems...

The file podspec file sets a `prepare_command` that is run when the pod is installed (see [IDZSwiftCommonCrypto.podspec](https://github.com/iosdevzone/IDZSwiftCommonCrypto/blob/master/IDZSwiftCommonCrypto.podspec) lines 19-40). This script calls `GenerateCommonCryptoModule.swift` multiple times with the appropriate arguments to create the dummy module maps for all platforms. The module maps should be generated in the `Pods/IDZSwiftCommonCrypto/Frameworks` directory.

I'll try to see if I can reproduce the issue here. I've just update to 9.1 myself. If you find any other clues please let me know.

**Comment by iosdevzone** [comment]
OK, I think I see the issue.
CocoaPods maintains a cache, so even though you remove your Pods directory and Podfile.lock it is still using old module maps. You can find the cache at `~/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto`. Remove this directory, your `Podfile.lock` and `Pods` directory and rerun `pod install`. You should be good to go!

**Comment by iosdevzone** [comment]
Even better CocoaPods has a command to clean the cache. Use:

`pod cache clean IDZSwiftCommonCrypto --all`

see[ pod cache clean](https://guides.cocoapods.org/terminal/commands.html#pod_cache_clean) for more info

**Comment by csotiriou** [comment]
You are right. That was the issue. Thank you very much.

I have a feeling that this should be noted in the documentation, too.

**Comment by iosdevzone** [comment]
I'll add a note. I did't know about it until I looked into what might be causing the issue you are seeing!
