### ISSUE TITLE
Got this error when I try to install.

### ISSUE THREAD

**Issue by Abhishek2611** [iosdevzone/IDZSwiftCommonCrypto#81]
[!] /bin/bash -c 
set -e
touch prepare_command.txt
echo 'Running prepare_command'
pwd
echo Running GenerateCommonCryptoModule
# This was needed to ensure the correct Swift interpreter was 
# used in Xcode 8. Leaving it here, commented out, in case similar 
# issues occur when migrating to Swift 4.0.
#TC="--toolchain com.apple.dt.toolchain.Swift_2_3"
SWIFT="xcrun $TC swift"
$SWIFT ./GenerateCommonCryptoModule.swift macosx .
$SWIFT ./GenerateCommonCryptoModule.swift iphonesimulator .
$SWIFT ./GenerateCommonCryptoModule.swift iphoneos .
$SWIFT ./GenerateCommonCryptoModule.swift appletvsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift appletvos .
$SWIFT ./GenerateCommonCryptoModule.swift watchsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift watchos .

Running prepare_command
/Users/abhishek/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.10.0-4eef2
Running GenerateCommonCryptoModule
SDK: macosx
SDK Version: 10.13
SDK Path: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Successfully created module ./Frameworks/macosx/CommonCrypto.framework/module.map
ERROR: ERROR: Failed to determine SDK version for iphonesimulator
./GenerateCommonCryptoModule.swift:15:34: warning: 'characters' is deprecated: Please use String or Substring directly
   let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                ^
./GenerateCommonCryptoModule.swift:15:34: warning: 'characters' is deprecated: Please use String or Substring directly
   let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                ^
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphonesimulator'

**Comment by iosdevzone** [comment]
To figure the correct path to the SDKs this script runs the command:
````bash
xcrun --sdk iphonesimulator --show-sdk-path
````
It looks like this is failing on your system. To test this, open a terminal window and copy and paste the above command into it. 
Please also let me know which version of Xcode you are using, which version of macOS.
You should also make sure that `xcode-select -p` is pointing to your current Xcode.

**Comment by Abhishek2611** [comment]
=>I run that command & i got this
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator'

=>currently I am using Xcode version "9.2" & macOS version is "10.13.2"

**Comment by iosdevzone** [comment]
That's strange. OK, maybe `xcode-select` is pointing to the wrong location or maybe you don't have the command line tools installed.
What happens when you type `xcode-select -p`

**Comment by iOSKida** [comment]
I got the same error .. I found that my Xcode command line tool is not linked with the latest Xcode installed. I linked them and my script started working .
For linking command line tool with Xcode , open xcode -> preferences -> locations -> command line tools -> select the tool compatible to the Xcode version . I have Xcode v 9.2 , so I selected same command line tool version.

**Comment by iosdevzone** [comment]
@iOSKida once you selected the correct version of command line tools were you able to compile?
@Abhishek2611 any update on your situation?

**Comment by iOSKida** [comment]
@iosdevzone  Yes.. I was able to compile

**Comment by iosdevzone** [comment]
@iOSKida -- good! Thanks for offering more information of this!

**Comment by iosdevzone** [comment]
Looks like the issue here was `xcode-select` not pointing to the version of Xcode being used. Closing this for the moment.

**Comment by iosdevzone** [comment]
``

**Comment by KhairulRijl** [comment]
same issue on XCode 10.2 & swift 5 and i use 0.10.0 version (swift 4 on read me documentation), i 've done what you suggested but is not solve the issue, please help
