### ISSUE TITLE
Missing required module 'CommonCrypto'

### ISSUE THREAD

**Issue by mateo666** [iosdevzone/IDZSwiftCommonCrypto#82]
I'm getting this error when building on a new machine

AESCryptor.swift:10:8: Missing required module 'CommonCrypto'

Is there something I must do before using this framework ?

**Comment by iosdevzone** [comment]
@mateo666, the fake CommonCrypto module should be created the first time you build. (Or at install time if you are using CocoaPods). It should be automatic.

• How did you install the library: Carthage, CocoaPods or git clone from GitHub?
• Are you sure `xcode-select` is pointing to the correct version of Xcode?

Strange as it may sound, sometimes quitting Xcode and reopening solves some of these problems.

**Comment by BrijPatel15** [comment]
I'm having the same issue, yesterday it was working fine today I updated Xcode and I'm getting a build error saying that "No such module 'CommonCrypto'". I installed using CocoaPods, I've tried updating and the xcode-select method as well but nothing is working.

**Comment by BrijPatel15** [comment]
Okay, so it seems like deleting the pod completely and reinstalling it fixed my issue.

**Comment by mateo666** [comment]
Still getting this error when installing project on a new machine .
using Carthage to install the library.
Dragging the library into Xcode project.
Build and.... 
Missing required module 'CommonCrypto'

What's the fix ?

**Comment by iosdevzone** [comment]
With Carthage you have to manually ensure that your framework search path includes a path to the CommonCrypto module maps.

**Comment by mateo666** [comment]
which is where ... ? 
and how ?
maybe it should be specified under Carthage in the install process.

**Comment by iosdevzone** [comment]
I believe this is no longer a problem now that CommonCrypto is an official framework.
