### ISSUE TITLE
Missing Arguement for parameter 'byteCount' in call

### ISSUE THREAD

**Issue by BrijPatel15** [iosdevzone/IDZSwiftCommonCrypto#84]
Hello, 

I'm trying to implement the HMAC algorithm for my application and I get an error saying "Missing arguement for parameter 'byteCount' in call". As far as I can tell I've copied your example pretty closly.
my Key is a String, and Data is also as string as well. This is my function call
```
     let hmacVal = HMAC(algorithm: .sha1, key: key).update(data)?.final()
 ```

**Comment by iosdevzone** [comment]
Apologies for this. It looks like the README is lagging a little behind the code. Try:
```swift
     let hmacVal = HMAC(algorithm: .sha1, key: key).update(string: data)?.final()
```
In one of the updates to a new version of Swift (I don't recall which one), in an attempt to be more _Swifty_ `update` was changed from not requiring argument labels, to requiring them. 

I'll leave this open to remind me to update the docs; but please let me know if this solved your problem.

**Comment by iosdevzone** [comment]
I've added versions of `update` that do not require arguments, so the docs and code match now. Thanks for reporting this.
