### ISSUE TITLE
error when execute pod install

### ISSUE THREAD

**Issue by hx8563** [iosdevzone/IDZSwiftCommonCrypto#87]
handeMacBook-Pro:Multy-IOS hanxiao.hx$ pod install
Analyzing dependencies
Downloading dependencies
Installing Alamofire (4.7.2)
Installing Branch (0.25.0)
Installing ButtonProgressBar-iOS (1.0.1)
Installing Crashlytics (3.10.2)
Installing CryptoSwift (0.9.0)
Installing Fabric (1.7.7)
Installing Firebase (5.2.0)
Installing FirebaseAnalytics (5.0.1)
Installing FirebaseCore (5.0.3)
Installing FirebaseInstanceID (3.1.0)
Installing FirebaseMessaging (3.0.2)
Installing GGLInstanceID (1.2.1)
Installing GoogleToolboxForMac (2.1.4)
Installing IDZSwiftCommonCrypto (0.10.0)

[!] /bin/bash -c
set -e
touch prepare_command.txt
echo 'Running prepare_command'
pwd
echo Running GenerateCommonCryptoModule
# This was needed to ensure the correct Swift interpreter was
# used in Xcode 8. Leaving it here, commented out, in case similar
# issues occur when migrating to Swift 4.0.
#TC="--toolchain com.apple.dt.toolchain.Swift_2_3"
SWIFT="xcrun $TC swift"
$SWIFT ./GenerateCommonCryptoModule.swift macosx .
$SWIFT ./GenerateCommonCryptoModule.swift iphonesimulator .
$SWIFT ./GenerateCommonCryptoModule.swift iphoneos .
$SWIFT ./GenerateCommonCryptoModule.swift appletvsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift appletvos .
$SWIFT ./GenerateCommonCryptoModule.swift watchsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift watchos .

Running prepare_command
/Users/hanxiao.hx/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.10.0-4eef2
Running GenerateCommonCryptoModule
SDK: macosx
SDK Version: 10.13.4
SDK Path: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Successfully created module ./Frameworks/macosx/CommonCrypto.framework/module.map
ERROR: ERROR: Failed to determine SDK version for iphonesimulator
./GenerateCommonCryptoModule.swift:15:34: warning: 'characters' is deprecated: Please use String or Substring directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^
./GenerateCommonCryptoModule.swift:15:76: warning: 'init' is deprecated: Please use String or Substring directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                                                           ^
./GenerateCommonCryptoModule.swift:15:34: warning: 'characters' is deprecated: Please use String or Substring directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^
./GenerateCommonCryptoModule.swift:15:76: warning: 'init' is deprecated: Please use String or Substring directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                                                           ^
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphonesimulator'

**Comment by hx8563** [comment]
problem solved, thanks for your help!

**Comment by iosdevzone** [comment]
You're welcome. Thanks for checking out the library!

**Comment by KhairulRijl** [comment]
hello @iosdevzone, i've same issue when i using XCode 10 and swift 5 when other library dependency to 0.10.0 version

**Comment by Nurka11** [comment]
> hello @iosdevzone, i've same issue when i using XCode 10 and swift 5 when other library dependency to 0.10.0 version

Hi, do you have any solution??

**Comment by iosdevzone** [comment]
@Nurka11 Please open a new issue showing exactly what error messages you are seeing and I will try to help you out.
