### ISSUE TITLE
Decrypting image fails

### ISSUE THREAD

**Issue by srikanthsuryawanshi** [iosdevzone/IDZSwiftCommonCrypto#88]
Hello IDZ,

I have been using your library for encrypting and decrypting the image. 
I am facing an issue.

Usecase - 

 if I encrypt an image file - store it on documents folder and later, on need basis decrypt the image and take the decrypted content in memory - as data and then show as an image in the app.

Issue -
after few decryptions the data decrypted is not been able to convert into an image.

after decrypting the size of data is correct but it does not produce an image in the app or in a file stored on the device.

I will share more info with code soon.

**Comment by iosdevzone** [comment]
Hi @srikanthsuryawanshi, I've marked this as awaiting information. Without code I can't really be of much more assistance.

**Comment by srikanthsuryawanshi** [comment]
yes, empty iV was causing the issue. funny thing is, it was working for some part and then causing issues in unknown scenarios.

salt with 16 characters has solved many issues even in string encryption-decryption.

**Comment by srikanthsuryawanshi** [comment]
keeping this open so either documentation can be edited for including mandatory 16 character salt or fixing the code for accepting empty salt and handling it inside the library.

**Comment by iosdevzone** [comment]
Version 0.12.1 now enforces IV lengths. Thanks for reporting this issue.
