### ISSUE TITLE
Upgrade to Swift 4.2.1?

### ISSUE THREAD

**Issue by Jcarto** [iosdevzone/IDZSwiftCommonCrypto#89]
Please let us know if you are upgrading to swift 4.2 anytime soon?
thanks

**Comment by iosdevzone** [comment]
Just got a chance to look at this. Should have a new release out by next Monday. Sorry for the delay getting to this! Thanks for your patience.

**Comment by iosdevzone** [comment]
Apologies for continued delay. Day job getting in the way.

**Comment by Jcarto** [comment]
Any Progress??

**Comment by iosdevzone** [comment]
Oh my gosh! I am so sorry, I got slammed at my day job and this slipped my mind. I'll try to look at it this evening and push a release. Apologies for any inconvenience.

**Comment by Jcarto** [comment]
No worries, just eager to move along...

**Comment by iosdevzone** [comment]
OK, You should be good to go with version 0.11.3. I'm going to keep this issue open for a few more days. There are still some minor tweaks I'd like to do to the documentation and build.
