### ISSUE TITLE
Upgrade to swift5? :-)

### ISSUE THREAD

**Issue by drojid** [iosdevzone/IDZSwiftCommonCrypto#92]
Please let us know if You are planning to upgrade to Swift 5 anytime soon?
Yes, I know that support for 4.2 is fresh'n'crispy, but perhaps switching to swift 5 is just a smaller leap... :-)

Many thanks in advance!

**Comment by iosdevzone** [comment]
Hey there, sorry for the delay, just back from vacation. Yeah, Swift 5.0 should be quick and easy (famous last words!). I'll try to get to it over the next few days. Thanks for checking out the library.

**Comment by wdcurry** [comment]
gentle ping here as well... thank you.

**Comment by iosdevzone** [comment]
Thank you all for your patience. Just published 0.12.0 with Swift 5.0 support.
