### ISSUE TITLE
Problem when install pod

### ISSUE THREAD

**Issue by KhairulRijl** [iosdevzone/IDZSwiftCommonCrypto#93]
I have problem like this on xcode 10.2 & swift 5, using 0.10.0 version because other library requiered that

`[!] /bin/bash -c 
set -e
touch prepare_command.txt
echo 'Running prepare_command'
pwd
echo Running GenerateCommonCryptoModule
# This was needed to ensure the correct Swift interpreter was 
# used in Xcode 8. Leaving it here, commented out, in case similar 
# issues occur when migrating to Swift 4.0.
#TC="--toolchain com.apple.dt.toolchain.Swift_2_3"
SWIFT="xcrun $TC swift"
$SWIFT ./GenerateCommonCryptoModule.swift macosx .
$SWIFT ./GenerateCommonCryptoModule.swift iphonesimulator .
$SWIFT ./GenerateCommonCryptoModule.swift iphoneos .
$SWIFT ./GenerateCommonCryptoModule.swift appletvsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift appletvos .
$SWIFT ./GenerateCommonCryptoModule.swift watchsimulator .
$SWIFT ./GenerateCommonCryptoModule.swift watchos .

Running prepare_command
/Users/khairulrijal/Library/Caches/CocoaPods/Pods/Release/IDZSwiftCommonCrypto/0.10.0-4eef2
Running GenerateCommonCryptoModule
./GenerateCommonCryptoModule.swift:15:34: error: 'characters' is unavailable: Please use String directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^~~~~~~~~~
Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
    public var characters: String { get set }
               ^
`

**Comment by iosdevzone** [comment]
Hi there, sorry for the delay. Just back from vacation, I'll try to take a look at this over the next few days. Thanks for bringing this problem to my attention!

**Comment by alexander-larsson** [comment]
https://github.com/CocoaPods/Specs/tree/9543734012238c33ea018af5a4381459c13f0916/Specs/1/c/2/IDZSwiftCommonCrypto

You haven't added version 0.11.0 to the master Pod repo. (Or however that works) You can't install version 0.11.0 through CocoaPods. Maybe that is a quick fix or you need to make a 0.12.0 version to support Swift 5.

**Comment by alexander-larsson** [comment]
Sorry seems like there is a version 0.11.3 available though CocoaPods somehow. I usually just look at the releases page on GitHub and assume the CocoaPods releases are the same numbers. This issue is resolved for me with 0.11.3 version of the pod 🙂

**Comment by wdcurry** [comment]
This is still happening at my end.

**Comment by iosdevzone** [comment]
@wdcurry What combination of Xcode/Swift/IDZSwiftCommonCrypto are you using? Have you updated Xcode recently? If so, did you clear your CocoaPods cache?

**Comment by wdcurry** [comment]
I am typically always at the latest bits but admit to not clearing the pod cache. I can try that shortly, thank you.

**Comment by iosdevzone** [comment]
@wdcurry Hopefully that will solve the problem. The podspec has not contained a prepare_command for quite some time, so I'm a bit confused about how this could be happening. I appreciate any further info you can give me!

**Comment by wdcurry** [comment]
I think I will leave this for now, as I have numerous projects that get touchy with such things. I think I have another vector to encryption success, but thank you!

**Comment by iosdevzone** [comment]
OK, well, sorry I could not solve the problem for you. I'll close this issue out for the moment, but if you chose to revisit just let me know. Good luck with your project!
