### ISSUE TITLE
New Swift 5.0 initializer parameters need commented documentation.

### ISSUE THREAD

**Issue by emtjoshhart** [iosdevzone/IDZSwiftCommonCrypto#97]
Small issue.  Not that I need this, sometimes I forget in my own projects and then later regret it down the road.  Could you please add the comment parameters for the new parameters?

For example: 
`
    // MARK: - Low-level interface
    /**
        - parameter operation: the operation to perform see Operation (Encrypt, Decrypt)
        - parameter algorithm: the algorithm to use see Algorithm (AES, DES, TripleDES, CAST, RC2, Blowfish)
        - parameter keyBuffer: pointer to key buffer
        - parameter keyByteCount: number of bytes in the key
        - parameter ivBuffer: initialization vector buffer
    */
    public init(operation: Operation, algorithm: Algorithm, options: Options,
                keyBuffer: UnsafeRawPointer, keyByteCount: Int,
                ivBuffer: UnsafeRawPointer, ivByteCount: Int)
    {`

**Comment by iosdevzone** [comment]
Good point! I'll take a look at it as soon as I get a moment.

**Comment by iosdevzone** [comment]
So i thought I'd missed out on a bunch of stuff, but then it was just this:
 - parameter ivByteCount: the length of the initialization vector `ivBuffer` in bytes
I think #98 closes this.

**Comment by iosdevzone** [comment]
Found a few more undocumented entities. PR #98 fixes all of these. Jazzy reports no undocumented public symbols. This will be in the next release. This should happen in the next few days as I want to get going on Xcode 11 support.
