### ISSUE TITLE
Xcode 11 support

### ISSUE THREAD

**Issue by rjchatfield** [iosdevzone/IDZSwiftCommonCrypto#99]
When compiling with Xcode 11, we get these compiler errors:

- Use of unresolved identifier 'kCCModeF8'
- Use of unresolved identifier 'kCCModeLRW'
- Use of unresolved identifier 'kCCModeXTS'

**Comment by rjchatfield** [comment]
Suggestion, remove 3 cases:

1. `StreamCryptor.Mode.F8` (Unimplemented)
2. `StreamCryptor.Mode.LRW` (Unimplemented)
3. `StreamCryptor.Mode.XTS`

**Comment by iosdevzone** [comment]
I'll be creating a branch in the next few days. I want to push one more release out on master before I create the branch. (Any also I'm too busy playing with `SwiftUI` at the moment 🤓

**Comment by khatchik** [comment]
Any news when this is going to be fixed? We are trying to ship a Mac App and this is one of the libraries blocking us :)

**Comment by iosdevzone** [comment]
Apologies, I've been very busy at my day job. I'll try to take a look at it this evening.

**Comment by khatchik** [comment]
no worries mate, we still have a month to sort this out. If you can push a fix in the next 30 days, The Atlassian iOS/Mac Team will thank you a lot :)

**Comment by iosdevzone** [comment]
Thanks for you patience. Just merged PR #100 that fixes this. Available as 0.13.0 on CocoaPods. Let me know if run into any issues!
Good luck with your release!

**Comment by khatchik** [comment]
Thanks mate!
